### ISSUE TITLE
Bug 1103041 - Navbar at /explore expands(doubles) because of increased links

### ISSUE THREAD

**Issue by tanay1337** [mozilla/webmaker.org#1014]
After logging in, at https://webmaker.org/en-US/explore , upon scrolling down, the navbar expands(doubles) because of increased links. This effect was probably not expected. Earlier the user-box and the links fixed in half the space. This messes up the UI.

Screenshot: https://bug1103041.bugzilla.mozilla.org/attachment.cgi?id=8526885

**Comment by thisandagain** [comment]
Fixed in the new navigation / IA! :smile:
