### ISSUE TITLE
Clean up locale strings and validation

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1066]
* check strings in locale files and angular/nunjucks templates to see if there are unused or unrepresented strings
* set up better validation with `grunt validate` (should be connected to recent versions of `grunt-gettext-finder`, and `grunt-angular-i18n-finder`
* separate strings from locale json files into independent angular/nunjucks files so that `grunt validate` works properly

---------

- [x] Remove old EOY locale file and its content https://github.com/mozilla/webmaker.org/pull/1075
- [x] separate all locales into its own file https://github.com/mozilla/webmaker.org/pull/1092
- [x] update grunt gettext/i18n finder and integrate them https://github.com/mozilla/webmaker.org/pull/1083
- [x] hook grunt validate for l10n with travis
- [x] update on transifex
- [x] make sure we add missing strings https://github.com/mozilla/webmaker.org/pull/1078

**Comment by secretrobotron** [comment]
e.g. strings that are in html files, but not in locale json string files
* Your badge was issued successfully.
* Search gallery
* Make successfully reported

**Comment by simonwex** [comment]
@alicoding what sort of tooling effort would this be to add a convincing validator to Travis?

**Comment by alicoding** [comment]
I have created grunt plugin for both angular and gettext to validate and
find unused strings except our project using both Angular and nunjucks
which makes it harder to automate these since we are sharing the locale
files for both frameworks and makes it hard / impossible for my plugin to
do its job. Now I just need to do some clean up manually and make sure it
can be setup with Travis.

**Comment by alicoding** [comment]
- [ ] Remove old EOY locale file and its content https://github.com/mozilla/webmaker.org/pull/1075
- [ ] separate all locales into its own file
- [ ] update on transifex

**Comment by alicoding** [comment]
This is all completed :)

I will work on document this with the handbook soon.
