### ISSUE TITLE
Send announcement to Transifex community to ask about localizing CTA

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1069]
There is some concern that the CTA in the wireframe (see below) will be lost outside of the English-speaking community.

Need to send an announcement to the Transifex community to ask them to weigh in on whether or not "I :heart: ___________" conveys the right (or any) meaning in other locales.

![](http://1.bp.blogspot.com/-6VRsevY6Gik/VKqtz9EQ2KI/AAAAAAAACGQ/thcTk1xAiHQ/s1600/5.png)

@iamjessklein, @HPaulJohnson thinking about saying something like this:

> Hello!
> 
> We're working on a completely new design for our splash page on webmaker.org. The idea is to invite users to edit the page they see by filling in the blank in "I <3 _________". Our question to you is this: does "I <3 __________" make sense cross-culturally? e.g. "I <3 cupcakes" or "I <3 the web" to convey that I love cupcakes and the web.
> 
> Thanks!
> 
> [link to above image].

**Comment by secretrobotron** [comment]
Actually, I should add some wording about how the page will be saved and displayed on explore.

**Comment by HPaulJohnson** [comment]
@secretrobotron with the addition of what happens next (saved, then displayed on explore) this works for me.

**Comment by alicoding** [comment]
@secretrobotron yes we could use Transifex interface to send an announcement to all of our translators here. I can help you doing that tomorrow through vidyo or something if you like.

**Comment by secretrobotron** [comment]
> Hello!
> 
> We're working on a completely new design for our splash page on webmaker.org. The idea is to invite users to edit the page they see by filling in the blank in "I <3 _________". Our question to you is this: does "I <3 __________" make sense cross-culturally? e.g. "I <3 cupcakes" or "I <3 the web" to convey that I love cupcakes and the web. The "editing" the user does will be saved as a webpage (just as x-ray goggles would do), and displayed on our Explore page (https://webmaker.org/explore).
> 
> Thanks!
> 
> Check out the new design here: https://camo.githubusercontent.com/1a9a7d273923251061e82cd692ae055fb79bcc74/687474703a2f2f312e62702e626c6f6773706f742e636f6d2f2d365652736576593647696b2f564b71747a394551324b492f41414141414141414347512f746863546b3178416948512f73313630302f352e706e67

**Comment by secretrobotron** [comment]
Done! (Thanks @alicoding !) https://www.transifex.com/projects/p/webmaker/announcement/3662/

Waiting for replies.

**Comment by secretrobotron** [comment]
According to the transifex thread, the phrase works in these langs/locales:
* Farsi
* Portuguese (BR)
* Dutch
* Russian
* India
* Indonesia
* Spanish
* Chinese
* Italian
* German
* French
* Some Arabic-speakers (getting confirmation on this one)

**Comment by xmatthewx** [comment]
Excellent. Seems like this is plenty good enough to pursue and then test on production.

**Comment by thisandagain** [comment]
:+1:
