### ISSUE TITLE
Dig up previous research on "Remix" vs. other CTAs

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1070]
The new on-boarding experience will probably have a big button to start the saving experience. In @iamjessklein's design, the button says "Remix", but @cassiemc points out that we're not quite sure that's the word to use.

What research do we already have on this subject? What words can we test?

/cc @HPaulJohnson, @adamlofting 

![](http://1.bp.blogspot.com/-6VRsevY6Gik/VKqtz9EQ2KI/AAAAAAAACGQ/thcTk1xAiHQ/s1600/5.png);

**Comment by HPaulJohnson** [comment]
Including @edrushka for her thoughts as well. 

Control: Remix

Test Ideas (throwing as many things out as I can to inspire other/better ideas, starring the ones I think are most appropriate): 
Make*
Make It
Make Yours
Make Something
Create
Create Your Own
Create Yours
Start
Get Started *
Start Creating
Go*
Hack It
Next* (think something super straightforward and typical; update and refresh are other examples like this)
Modify
Update
Refresh

Whatever test(s) we come up with for button, we'd need to have sync subhead copy as well.

**Comment by secretrobotron** [comment]
I like "Make", "Next", and "Go". 

How about "Save" though? Most of these options feel less like they address what's actually going to happen when I click the button. "Create" is pretty good, but I think "Save" might be more accurate (?).

**Comment by secretrobotron** [comment]
@thisandagain, @cassiemc, @iamjessklein any thoughts about what to pursue first?

**Comment by cassiemc** [comment]
I like 'get started', 'go' 'next' as they seem forward-propelling words that are in the spirit of the ask. Less excited about Make, as it seems more vague, but eager to see test results.

**Comment by thisandagain** [comment]
Agreed with @cassiemc 's instincts here. I'd like to test "Make" and "Remix" as I feel like that would be incredibly useful to inform some of the work that we are doing with both the mobile and desktop / tablet tools:

- Get Started
- Go
- Next
- Make
- Remix

**Comment by secretrobotron** [comment]
Excellent! We'll go with that list for now.

**Comment by sole** [comment]
I am not sure I am responding to the right things but I will just translate to Spanish those last bullet points. Bear with me as I'm not used to your way of working :D

* Get started - Vamos allá
* Go - ¡Vamos!
* Next - Siguient
* Make - Crear
* Remix - Remezclar

Sorry about the delay, @secretrobotron -it's been some hectic days this week!

**Comment by secretrobotron** [comment]
@sole :+1: no problem! thanks! these are great.
