### ISSUE TITLE
Build on-boarding experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1072]
Build the on-boarding experience designed by @iamjessklein and @xmatthewx.

* should be a splash page variant (see `home2.html`, `home3.html`, etc.)
* should save the entire page à la x-ray goggles

**Comment by secretrobotron** [comment]
Based on UX work done in #1073.

**Comment by ScottDowne** [comment]
If we're saving the whole page, why not just use goggles for this?

**Comment by secretrobotron** [comment]
goggles would work technically, but it might be too much tooling for something that we need to keep *real* simple. Discuss w/ @xmatthewx in #1073 to unlock secrets.

**Comment by secretrobotron** [comment]
- [ ] fake typing in the input box
- [ ] click button to save & move on
- [ ] join screen w/ preview and "agree" box
- [ ] connect to login3 modal
- [ ] landing (logged in) CTA

**Comment by secretrobotron** [comment]
blocks #1082

**Comment by xmatthewx** [comment]
We might need to scale the type based on character count and width of the entry space. Mobile could suffer without it.

**Comment by xmatthewx** [comment]
Assets in dropbox: https://www.dropbox.com/sh/r5o9qvrfbs9nvz4/AACKOzDYfED0e7NMeAv594gua?dl=0

**Comment by xmatthewx** [comment]
Final splash: https://redpen.io/tw577ea2513e0dcdce
Mobile view: https://redpen.io/md1632a6c53a033b86

Final signup: https://redpen.io/dfb517c69e56050443
Mobile view: https://redpen.io/sfdd780957757e331b

**Comment by secretrobotron** [comment]
@ScottDowne see https://github.com/mozilla/webmaker.org/issues/1079#issuecomment-69835084 for copy to use.

**Comment by secretrobotron** [comment]
@ScottDowne see https://github.com/mozilla/webmaker.org/issues/1073#issuecomment-69811917 for final design.

**Comment by xmatthewx** [comment]
@ScottDowne - here's a view of the narrow screen (< 760px, when nav becomes hamburger). If you reduce the margins, you should be able to get the arrow in good alignment.

https://redpen.io/cx28905f7923498c99

**Comment by xmatthewx** [comment]
Sorry. I said that wrong. After the hamburger appears at < 768px we should jump to a wide mobile layout. Let me know if this gives you any trouble. 

before break https://redpen.io/cx28905f7923498c99
after the break https://redpen.io/gk383a15c1f32ac43c

**Comment by k88hudson** [comment]
[ ] text is misaligned in Chrome + Safari
[ ] text overflow cut off on mobile, text is too big
[ ] heart is pixelated on retina screens
[ ] too much space between heart and 'sharing' (should be even to the distance between I and heart)

Also IMO the typing is too slow

**Comment by HPaulJohnson** [comment]
On the signup screen can we change "craft" to "make" to keep our language consistent: 

"Now, learn to make and share more of your favorite things on the web."

**Comment by ScottDowne** [comment]
Ali, here is a pull request that fixes the lings above that Kate listed: https://github.com/mozilla/webmaker.org/pull/1102

**Comment by xmatthewx** [comment]
Android 4.4.4 
Chrome

Alignment of input field is low (as it is in Chrome Desktop). The line cuts across letters.

![screenshot 2015-01-16 14 38 26](https://cloud.githubusercontent.com/assets/53411/5783114/4b06cc5c-9d8e-11e4-98c4-ed3466798de6.png)

**Comment by iamjessklein** [comment]
[] on the sign up screen - the spacing between the button and input box is too tight
[] on the sign up screen - the button and input box should be aligned left
[] in confirmation modal - the checkbox should either have fill or a check. It should have higher color contrast: 
![screen shot 2015-01-16 at 2 43 15 pm](https://cloud.githubusercontent.com/assets/535012/5783111/49ddf3d2-9d8e-11e4-8ba3-7792de35fb47.png)

**Comment by alicoding** [comment]
The alignment of the text looks good in all three browsers (Chrome, Firefox and Safari)
Looking at mobile view and it does seems to be fine now.
Heart looking good now with retina
Heart and sharing doesn't have much spacing anymore.

**Comment by xmatthewx** [comment]
Chrome 39.0 & Firefox Dev
OS X 10.10.1

@media - The arrow points to the wrong place in screen width from 480px to 768px.

Let's match the layout used for < 480px screen for everything less than 768. 

![screenshot 2015-01-16 15 00 01](https://cloud.githubusercontent.com/assets/53411/5783403/8a64d766-9d90-11e4-9c36-aa025f191b21.png)


![screenshot 2015-01-16 15 03 03](https://cloud.githubusercontent.com/assets/53411/5783431/c85ab1da-9d90-11e4-98c4-054f9472d362.png)

**Comment by xmatthewx** [comment]
:watch:  Is anyone using a watch to view webmaker??? :watch:  
The arrow breaks on screens less than 220px. ;)

![screenshot 2015-01-16 15 22 05](https://cloud.githubusercontent.com/assets/53411/5783732/bb173586-9d93-11e4-909b-57ceb4214a1f.png)

**Comment by k88hudson** [comment]
Also broken on my tamagochi

**Comment by xmatthewx** [comment]
FF Dev on OS X 10.10

Field and Button collide

![screenshot 2015-01-16 15 46 55](https://cloud.githubusercontent.com/assets/53411/5784090/195f9f4a-9d97-11e4-844b-e90fc0b22bdf.png)

**Comment by xmatthewx** [comment]
Blue background loads with delay on second screen. Can we fetch it after first screen loads?

**Comment by k88hudson** [comment]
This is what it looks like in IE11:
![webmaker](https://cloud.githubusercontent.com/assets/1455535/5784274/bbc52bd2-9d98-11e4-8d31-37fdb9567c58.PNG)

* next button overhangs on the right side of the screen
* giant x on the right of the text box
* heart doesn't show up at all

**Comment by k88hudson** [comment]
Actually the broken link on the image seems to be on all retina screens.

**Comment by xmatthewx** [comment]
Second screen scales nicely. :+1: 

Nice job handling long strings. Looks good in thumbnail. :+1: 

 - [ ] add limit to 50 characters

**Comment by xmatthewx** [comment]
True or false: the experience would be nicer if we selected all text onfocus for easier rewrite by the user. Anyone have an opinion?

**Comment by secretrobotron** [comment]
@xmatthewx :+1: i vote yes

**Comment by iamjessklein** [comment]
:+1: i vote yes as well

**Comment by secretrobotron** [comment]
Filing issues here: https://github.com/mozilla/webmaker.org/milestones/On-boarding%20Experience%20v1

**Comment by secretrobotron** [comment]
Done :).
