### ISSUE TITLE
Design UX for on-boarding experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1073]
Need to provide UX for the on-boarding experience based on @iamjessklein's work (http://jessicaklein.blogspot.ca/2015/01/shall-we-dance-on-boarding-webmakers.html).

![](http://1.bp.blogspot.com/-6VRsevY6Gik/VKqtz9EQ2KI/AAAAAAAACGQ/thcTk1xAiHQ/s1600/5.png)

**Comment by ScottDowne** [comment]
I'm going to need a better idea as to what happens once remix is clicked and what we expect that to look like.

By looking at the image, the first thing that comes to mind is I can fill in the blank using html. Is that all it does? Or can I change anything on the page, and filling in the blank is just the example we're showing people?

I'm hesitant to build a publishing tool that can save a whole page if it's just saving an inserted text string.

**Comment by xmatthewx** [comment]
I agree. I don't believe that publishing adds value to this experience unless we deliver someone to their profile or show their thing in the gallery, especially since they are adding text, not html or css to something that looks like a form field.

**Comment by xmatthewx** [comment]
@ScottDowne -- would it be easier to augment goggles as it [currently will appear](https://cloud.githubusercontent.com/assets/53411/5649369/2fb828ba-9663-11e4-949b-d2916f59ecb3.png) to guide the user, or would it be easier rework the hackable snippet?

Goggles has 2 major UX blockers:

 1. To start, a user needs to intuit that they can click a weird pretty box to do something (invisible on tablets). Or, we need to augment goggles.
 2. To finish using goggles, a user needs to notice a tiny publish button in the bottom right corner AND feel ok about doing something big and public. Or, we need to augment goggles. 

The [hackable snippet](https://brianloveswords.github.io/webmaker-firefox-snippet/) offers a similar experience, but is built to hold your hand through the process.

**Comment by ScottDowne** [comment]
The biggest advantage to using goggles is we get saving and publishing for free.

If publishing is not a goal, this becomes much easier and goggles no longer makes much sense :)

**Comment by xmatthewx** [comment]
I propose that we simplify and emulate the experience. Skip the tool and publishing for a cleaner experience. Fake it 'til we make it. Finish with a targeted CTA to do the real thing: https://redpen.io/hx206df20470e8804a

**Comment by ScottDowne** [comment]
Question, looking at the old webmaker.org homepage, how much are we removing?

**Comment by xmatthewx** [comment]
I believe this will replace the blue box (and everything in it) under the primary menu.

**Comment by ScottDowne** [comment]
But leave the stuff under the blue box?

**Comment by secretrobotron** [comment]
Yep. Just the top section is changed. That's what we're A/B testing atm.

**Comment by ScottDowne** [comment]
Are any assets I need, like images, going to be provided or is it waiting for me to request what I need?

I'm not sure yet what I need, but it looks like a heart image, maybe the torn paper effect, which looks like more than one, and maybe the word love?

For now I can place in something temporary.

**Comment by secretrobotron** [comment]
Unless @xmatthewx has something already, I'd suggest going with some stand-in stuff for now. Are you able to get the key functionality working first?

**Comment by secretrobotron** [comment]
Just coming out of a group huddle. Here are the thoughts:
- we have a good idea of which design direction to take
- @xmatthewx will iterate further and upload to redpen tonight
- @ScottDowne will chug along on #1072
- @edrushka and I will meet on Monday to brainstorm copy fill in @xmatthewx's design
- logged-in users will be directed at /explore, while new users will run through @xmatthewx's flow and be directed to x-ray goggles through login's modal sequence (i.e. no new splash page to land on)

**Comment by secretrobotron** [comment]
blocks #1082

**Comment by xmatthewx** [comment]
Next round posted for review. [Drop feedback in redpen](https://redpen.io/va0771ff858117e072). 

![heart-8](https://cloud.githubusercontent.com/assets/53411/5673201/d7725fae-9766-11e4-9aaa-518a94840942.png)

![heart-mobile](https://cloud.githubusercontent.com/assets/53411/5673236/17dbfafa-9767-11e4-92cd-682a9a921768.png)

**Comment by xmatthewx** [comment]
Nearing finalized versions.

 - large screen: 
  - splash: https://redpen.io/va0771ff858117e072
  - sign up: https://redpen.io/dfb517c69e56050443
 - small screen: 
  - splash: https://redpen.io/md1632a6c53a033b86
  - sign up: https://redpen.io/sfdd780957757e331b

**Comment by xmatthewx** [comment]
Since photos have tested well, we might also run something like this: 

 - large screen:
   - splash with photo: https://redpen.io/nw19838b795b26f0af

**Comment by xmatthewx** [comment]
@cassiemc - take a look at updated color and the alt version using a photo in the background. Links in 2 comments above.

**Comment by xmatthewx** [comment]
Final splash: https://redpen.io/tw577ea2513e0dcdce
Mobile view: https://redpen.io/md1632a6c53a033b86

Final signup: https://redpen.io/dfb517c69e56050443
Mobile view: https://redpen.io/sfdd780957757e331b

Assets: https://www.dropbox.com/sh/r5o9qvrfbs9nvz4/AACKOzDYfED0e7NMeAv594gua?dl=0

![heart-note](https://cloud.githubusercontent.com/assets/53411/5728301/42405c4a-9b37-11e4-9d31-59b0b7f1f4ce.png)

**Comment by secretrobotron** [comment]
Thanks @xmatthewx !

**Comment by cassiemc** [comment]
Great work @xmatthewx! Go team go.
