### ISSUE TITLE
Come up with localized tests for on-boarding CTA button

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1077]
Just as we're testing the text on the button in the on-boarding experience in #1070 in English, we should also test in a handful of locales (to start).

* What locales can we test with initially? (choose 5?)
* Who are the community members from those locales that can help us choose the language? (ideally people that can jump in here and take part)

/cc @thornet, @HPaulJohnson, @alicoding

**Comment by alicoding** [comment]
Looking at the history of translation and how active our community in each locale. I would suggest these languages:

1. French
2. German
3. Indonesian
4. Spanish
5. Portuguese

**Comment by thisandagain** [comment]
By traffic over the past 30 days, I would suggest the following. Looks like we are fairly aligned with the exception of Russian / Indonesian:

1. English - en-us (50.07%)
2. French - fr (9.02%)
3. Russian - ru-ru (7.40%)
4. Spanish - es-es (5.71%)
5. German - de (5.30%)
6. Portuguese - pt-br (4.12%)

**Comment by alicoding** [comment]
I might be able to find someone who speaks and can help translate our content into Russian in this case.

**Comment by LauraHilliger** [comment]
German in order of preference:
umwandeln
individualisieren
mutieren (this actually means mutate, but...no but, it means mutate :)
anpassen
bearbeiten
ändern
selber machen 

Happy to explain those nuances if you need me to!

**Comment by secretrobotron** [comment]
@LauraHilliger yeah! I would love to understand them. (and thanks!)

**Comment by LauraHilliger** [comment]
* umwandeln (kind of like "change around")
* individualisieren (individualize - but in german it's used much more often than in english)
* mutieren (this actually means mutate, but...no but, it means mutate :)
* anpassen ("make this fit to YOU" anpassen is generally used to say that you modified something to be personal. Like personalized but not as..arrogant)
* bearbeiten (edit)
* ändern (change)
* selber machen (make it yourself; DIY)

**Comment by LauraReynal** [comment]
* Crée le tiens ( make your own)
* à toi de jouer ! ( your turn to play/create) ****
* à ton tours ! ( your turn) 
* customise le ( customize it) 
* Modifie le ( modify it ) 
* Personalise le ! ( personalize it ) 
* C'est parti ( let's start, GO ) ****
* Commencer ( start ) 


My 2 favorites as far as CTAs are concerned are "à toi de jouer ! ( your turn to play/create)" and "C'est parti ( let's start, GO )"

cc @secretrobotron

**Comment by LauraReynal** [comment]
Given that it's about making your own, after all it might be better with the second one : your turn to create : "A toi de jouer" , which has a playful connotation.

**Comment by soapdog** [comment]
Portuguese version:

* Crie o seu ( make your own)
* Sua vez de jogar/criar! ( your turn to play/create) ****
* sua vez! ( your turn)
* Customize ( customize it)
* Modifique ( modify it )
* Personalize( personalize it )
* Vamos começar!( let's start, GO ) ****
* Começar ( start )

There is an "issue" with all the phrases such as "modify it" that were translated to "Modifique", we're missing the "it" part mostly because depending on what goes after the verb with change the article.

**Comment by secretrobotron** [comment]
Via @sole:
* Get started - Vamos allá
* Go - ¡Vamos!
* Next - Siguiente
* Make - Crear
* Remix - Remezclar
