### ISSUE TITLE
Craft copy for on-boarding experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1079]
@xmatthewx drew up some designs to progress the UX of the on-boarding experience, and we'd like it to include some compelling words to explain what's going on and get users to interact.
![](https://dl.dropboxusercontent.com/u/7054348/heart-3.png)
![](https://dl.dropboxusercontent.com/u/7054348/sign-up-1.png)

/cc @edrushka

**Comment by secretrobotron** [comment]
block #1072

**Comment by xmatthewx** [comment]
Here's the step that includes the email address field. It includes some copy to give a sense of length. https://redpen.io/dfb517c69e56050443

**Comment by xmatthewx** [comment]
For the fill-in-the-blank text, it would be great to have a short option and a long option. Design can have an arrow that points to the space for clarity. 

Some untested ideas:
 - What do you love on the web? `Short`
 - What do you love? Learn to make it on the web with us. `Medium`
 - What do you love? Let’s fill the web with more of it. Start now by naming one of your favorite things here. `Long`

**Comment by xmatthewx** [comment]
Would be good to have 2 or 3 options to test as the default ♡s.

Example:
 - I ♡ sharing
 - I ♡ animated gifs
 - I ♡ debates with friends

Again, short and long would be great.

**Comment by xmatthewx** [comment]
Short copy will be important for this to survive on mobile. More than usual since the prompts really need to connect with the fill-in-the-blank and the thumbnail of what you just made. :worried:

**Comment by xmatthewx** [comment]
Nearing finalized versions.

 - large screen: 
  - splash: https://redpen.io/va0771ff858117e072
  - sign up: https://redpen.io/dfb517c69e56050443
 - small screen: 
  - splash: https://redpen.io/md1632a6c53a033b86
  - sign up: https://redpen.io/sfdd780957757e331b

**Comment by secretrobotron** [comment]
- maybe just stick with "Next" for the button
- come up with a list of words for the editable textbox
- change the text in the signup phase ("well done" feels too fake, finite)

**Comment by edrushka** [comment]
@secretrobotron @HPaulJohnson and I hacked some copy. It's here: https://studiomofo.etherpad.mozilla.org/splash-page-copy

**Comment by xmatthewx** [comment]
@edrushka - I like the sign up page copy. Nice and clean. 

For the splash page, thanks for the long list of options. As we whittle it down to 2 or 3, let's lean toward common words and away from mofo lingo. I think that "sharing gifs" is better than "maker parties" since our audience is firefox users and youth on the web at-large, rather than current webmakers in the hive network.

**Comment by edrushka** [comment]
Works for me!

**Comment by secretrobotron** [comment]
Results!

##### Header
Good start

##### Sub-head
Now, learn to craft make and share more of your favorite things on the web.
I actually prefer "make" to "craft" as that's more on brand and that's our real differentiator - learning by making.

##### Words to use in the text box
* Learning
* Sharing gifs
* Foxes
* Making Memes
* Hacking
* Disappearing Cats
* Mashups

**Comment by xmatthewx** [comment]
Excellent. I believe in an earlier meeting I suggested we auto type 2-3 phrases in the blank. I believe the group decided to just type one phrase. 

What do you think is most universal? Sharing gifs, Making memes?

**Comment by HPaulJohnson** [comment]
Sharing gifs is probably more common but I like (and vote for) "making memes" because it's closer to the spirit of what we are leading people towards with Webmaker. 

Since we are using a single phrase and this is such prime real estate, it is definitely worth testing now or in the future.

**Comment by secretrobotron** [comment]
For now, we'll use a whole bunch of them; they can just rotate while you sit on the page, and pick a random one to start with when you land there. Would be great to run a test when we get optimizely re-working.
