### ISSUE TITLE
Save content new users create during on-boarding experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1081]
A question arose from talking about #1073 about saving & publishing the edits that new users make during the on-boarding experience. Essentially, it would be an x-ray goggles publish operation, and most of the makes would look 99% identical.

* Will a new user feel more engaged/interested if we publish their content right away?
  * Will they be deterred if we don't publish, but just direct them to x-ray goggles?
* Does this approach introduce too much similar, uninteresting content into /explore?
  * Or will users feel good about seeing their content up on webmaker right away?

**Comment by xmatthewx** [comment]
I added the thumbnail to the UX because I think it's the right sized reward for the user's actions AND it's a reward they can actually see.  

Users aren't likely to see the published results unless they really dive deep into Webmaker. IMHO, I'm not sure it's worth the work.

**Comment by secretrobotron** [comment]
> unless they really dive deep into Webmaker
Unless, of course, we show it to them. e.g., when they visit /explore, or when they look at their profile.

**Comment by xmatthewx** [comment]
> Unless, of course, we show it to them.

True. It'd be great if we could do that, but my sense was that it was out of scope. If not, then we can choose the modal or a destination. I'd vote like this:

 1. _Explore_ with their thing at the top
 2. Try goggles modal
 3. Profile

**Comment by secretrobotron** [comment]
:+1: I think you're right about scope. These "makes" probably won't be unique enough to provide real value even if we showed them to users.
