### ISSUE TITLE
Splash page A/B tests only work for en-US

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1085]
Try visiting any locale other than en-Us. You will always see the "The web is yours" variant.

* https://webmaker.org/es
* https://webmaker.org/pt-br
* https://webmaker.org/de
* etc...

This probably needs to be fixed in Optimizely. @simonwex: angular+optimizely pain-point :/ ?

/cc @HPaulJohnson

**Comment by HPaulJohnson** [comment]
Hmm. I just tweaked the config in optimizely hoping I'd fix. I originally the experiment's "URL targeting" set for either webmaker.org/en-US or webmaker.org and I removed the /en-US. So the experiment is now just running off the webmaker.org URL. 

The variants are still serving as expected but unfortunately the non-en locales are all still defaulting to "the web is yours" variant. Others should verify in the morning but doesn't look like this tweak changed. 

If there are other ideas about how to better configure for the localized versions let me know. 

Regardless, when evaluating results in GA we should just be comparing /en-US vs. /en-US/home-2, etc. as those results should be unaffected.

**Comment by secretrobotron** [comment]
Ah that was my fault. Changed it to work with both because https://webmaker.org/en-US never uses another variant.

AFAICT, like @HPaulJohnson said, non-en locales are still pointing at that single variant. That's still a problem.

I just tried adding a regex to optimizely (`https://webmaker.org/[a-zA-Z][a-zA-Z]-[a-zA-Z][a-zA-Z]`) which almost worked, but it still pointed back to the en-US version.

What might work is taking the `en-US` out of the destinations that the Optimizely router points to. @HPaulJohnson thoughts?

**Comment by HPaulJohnson** [comment]
@secretrobotron I stripped out en-US from all the redirects in optimizely. Looks like that may have fixed it. Double check and let me know?

**Comment by secretrobotron** [comment]
@HPaulJohnson Yeah. Definitely works for https://webmaker.org/, but not https://webmaker.org/en-US. Same with https://webmaker.org/pt-br/, https://webmaker.org/zh-CN etc.

Not sure how much of a problem is though. I bet some tiny % of people already have the locale string on the end of the url they use to get to webmaker.

**Comment by thisandagain** [comment]
I'd rather have this problem than the former. :wink: 

The % of folks who hit the locale specific version of the splash pages directly is fairly low as a % of new users.

**Comment by secretrobotron** [comment]
Ah that's great. Thanks @thisandagain, @HPaulJohnson . My nonsense is noted.
