### ISSUE TITLE
Makes profiles missing makes

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker.org#1087]
username.makes.org doesn't have any makes for me (tried 2 users). Events and Badges appear, but "Makes", "Likes" and "Teaching Resources" have no information in the profile.

**Comment by thisandagain** [comment]
Can you provide links to a few sample users?

May be related to https://github.com/mozilla-appmaker/appmaker/issues/2385 (cc @simonwex @jbuck )

**Comment by jbuck** [comment]
Oops, this is my fault. I fixed this bug on staging but I forgot to push to prod :disappointed: 

profile has now been pushed to prod, and we're good.

**Comment by thisandagain** [comment]
Thanks @jbuck

**Comment by thisandagain** [comment]
@LauraHilliger can you confirm that this is fixed for you in production?

**Comment by LauraHilliger** [comment]
I'm not getting anything on prod at the moment (https://webmaker.mofoprod.net right!? No error, just endless spinning), but it appears to have been pushed to wm.org last week. So, confirmed, this is fixed.

**Comment by thisandagain** [comment]
Production is just "webmaker.org". Thanks for confirming.

**Comment by LauraHilliger** [comment]
[ facepalm ]
