### ISSUE TITLE
Why are we dimming the checkbox label on hover?

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1089]
If I hover over a checkbox, it's dimmed.  That seems wrong.

![screenshot 2015-01-09 09 33 43](https://cloud.githubusercontent.com/assets/51278/5684156/ac59e306-97e2-11e4-9a84-aa1fb06c924d.png)

(the screen capture didn't catch the mouse cursor over the second line)

**Comment by thisandagain** [comment]
+1 It's a confusing interaction.

Proposed solution is to remove the hover state completely as to have it behave like a conventional check box control.

**Comment by iamjessklein** [comment]
:+1:  I second that
