### ISSUE TITLE
Typographic cleanup

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1094]
I find the type on this dialog to be not-quite-right:

![screenshot 2015-01-09 14 18 40](https://cloud.githubusercontent.com/assets/51278/5688312/7b6b4352-980a-11e4-93ad-2937e03cc63a.png)

The checkboxes feel too thin; the line width on the checkbox line copy feels too thin, especially given the light blue link colors.

And I suspect this is even more subjective, but the Capitalization Of the Title seems off too. I'd only capitalize Create and Webmaker.

**Comment by vazquez** [comment]
Yes @davidascher you are right on the ball. Some CSS changed while we were pushing things to production.

**Comment by iamjessklein** [comment]
sidenote: from an accessibility/ legibility perspective - I find the Open Sans light barely readable - particularly when it is that blue.

**Comment by gesa** [comment]
@davidascher @vazquez @iamjessklein: What do you think of this?
![](http://snaps.akibraun.com/ftwi4.png)

**Comment by davidascher** [comment]
checkbox grey seems super light on my screen, i'd suggest darkening a bit.  (also note that @vazquez has a new checkbox coming). apart from that, seems fine.

**Comment by gesa** [comment]
Should I just use the same color/thickness as the text input?

**Comment by gesa** [comment]
![](http://snaps.akibraun.com/8h3xk.png)

**Comment by iamjessklein** [comment]
:+1: for now that looks right. There really is not reason to differentiate the line weights and color here.

**Comment by vazquez** [comment]
Yeah that looks right :)
