### ISSUE TITLE
Button on second onboarding screen in wrong place

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1103]
Looks cramped, like it shouldn't be on a new line.

![screenshot 2015-01-16 14 46 00](https://cloud.githubusercontent.com/assets/403231/5783132/77678912-9d8e-11e4-9ed7-e8aabe280f29.png)

**Comment by secretrobotron** [comment]
Relates to https://github.com/mozilla/webmaker.org/issues/1072#issuecomment-70319781

**Comment by ScottDowne** [comment]
Should be fixed now. Reopen if it's broken still/again.
