### ISSUE TITLE
Wrong modal after signing up on webmaker

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1104]
Need to show the x-ray goggles modal.

![screenshot 2015-01-16 14 49 15](https://cloud.githubusercontent.com/assets/403231/5783194/e31992b8-9d8e-11e4-8e62-6733ff380026.png)

**Comment by secretrobotron** [comment]
Relates to https://github.com/mozilla/webmaker.org/issues/1072

**Comment by ScottDowne** [comment]
https://github.com/mozilla/webmaker-login-ux/pull/150

**Comment by secretrobotron** [comment]
fixes #148

**Comment by secretrobotron** [comment]
This is mostly fixed now. Only a couple fringe cases where it's a problem. https://github.com/mozilla/webmaker.org/pull/1132 will fix them.
