### ISSUE TITLE
Not redirected to explore after signing up

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1106]
After clicking "Let's Go" on the login modal (shown below), I just stay on the onboarding experience's second (blue) screen.

![screenshot 2015-01-16 14 49 15](https://cloud.githubusercontent.com/assets/403231/5783230/1ecce51c-9d8f-11e4-926e-78d327cf80e0.png)

**Comment by secretrobotron** [comment]
Relates to https://github.com/mozilla/webmaker.org/issues/1072

**Comment by ScottDowne** [comment]
This bug https://github.com/mozilla/webmaker.org/issues/1104 should display a "try goggles now" button instead, making this invalid, so closing.
