### ISSUE TITLE
"Tools" page is wonky

### ISSUE THREAD

**Issue by Melechuga** [mozilla/webmaker.org#1107]
"Tools" page -- in both English + Spanish at least -- are garbled.

![screen shot 2015-01-16 at 11 57 02 am](https://cloud.githubusercontent.com/assets/5815317/5783375/2b529c90-9d77-11e4-89ee-36b8e6c8294b.png)

**Comment by alicoding** [comment]
@Melechuga can you check your browser's `header` in the console/`network` tab and paste the information here? I'm curious about `Accept-Language` of your `Request headers`.

**Comment by secretrobotron** [comment]
@alicoding mine does it too.
```
Accept-Language:en-US,en;q=0.8,pt;q=0.6,de;q=0.4,zh;q=0.2
```

**Comment by Melechuga** [comment]
Accept-Language: "en-US,en;q=0.5"

**Comment by alicoding** [comment]
Fixed :) Thank you for the report @Melechuga
