### ISSUE TITLE
Slow down typing of initial word

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker.org#1111]
When I first load the page, "sharing" is already mostly typed out. Could we delay the start of that animation by a couple seconds so that people can "read" the page layout before getting drawn in by the animation? 

Using FF 35 mac.

**Comment by xmatthewx** [comment]
Delay typing until after page load is complete. Maybe add a slight pause beyond that. Don't slow down speed of typing itself.

**Comment by ScottDowne** [comment]
the delay is currently set to 1 second, and the dom has loaded. Sounds like a bug, but not sure yet how to reproduce.

**Comment by secretrobotron** [comment]
@ScottDowne it's pretty quick for me too. On a cache-cleared load, I see
- page load
- background crawls in (loads slowly)
- typing starts

...all within a second or so. We could slow down the start of the typing a bit more beyond that. Maybe another second?
