### ISSUE TITLE
Tweak background darkness & saturation

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker.org#1115]
I think the green background could be tweaked slightly for better readability of the yellow type, and a slightly richer, more inviting green.

Here's one to try – though @xmatthewx may want to alter the original for better quality.

![bkg-green](https://cloud.githubusercontent.com/assets/1186326/5784817/0e60b6c2-9d9e-11e4-9fba-cea6d27aec4a.jpg)

**Comment by secretrobotron** [comment]
ping @xmatthewx do you want to supply a better-quality one?

**Comment by cassiemc** [comment]
ping @vazquez as well - do you have vectors for this pattern?

**Comment by vazquez** [comment]
No vectors unfortunately, I created it in PS

**Comment by secretrobotron** [comment]
@vazquez @cassiemc cool to go ahead with the image above then?

**Comment by cassiemc** [comment]
@vazquez that's cool, can you share the source file?

**Comment by xmatthewx** [comment]
collecting patterns here: https://drive.google.com/folderview?id=0B_rbDAen9prkNXpOTzdpZ3NkUU0&usp=sharing

**Comment by vazquez** [comment]
https://dl.dropboxusercontent.com/u/43783651/Textures.psd

**Comment by cassiemc** [comment]
Fantastic! Here's the new asset. And it's down from 200k to 24...

![texture-green](https://cloud.githubusercontent.com/assets/1186326/5842769/9d4d8bd2-a175-11e4-9e55-7bffea024ebd.jpg)

Will move the psd to the drive folder.

**Comment by secretrobotron** [comment]
:heart: small file sizes. Thank you.

A bit confused about the difference between retina and non-retina sizing. Both of the current bg images are 2400x1420 @ 72dpi. Something I'm missing?

**Comment by cassiemc** [comment]
I tried doubling the resolution, but could only keep quality the same if it shrank the image, so I think that would still be pixelated on retina. Ricardo has a generator he is going to try. Looking into it.

**Comment by cassiemc** [comment]
Bobby – that was my bad, I generated the image with 'save for web' which doesn't let me save out at higher than 72dpi (catch up photoshop!). Anyway, still the same problem. @vazquez is looking into it.

**Comment by vazquez** [comment]
Here it is: https://dl.dropboxusercontent.com/u/43783651/Textures-geometric-green-assets.zip

**Comment by cassiemc** [comment]
And here they are:
![textures-geometric-green-2x](https://cloud.githubusercontent.com/assets/1186326/5844806/d493fa36-a184-11e4-85eb-c3a17ea6c219.jpg)
![textures-geometric-green](https://cloud.githubusercontent.com/assets/1186326/5844807/d4954576-a184-11e4-9f1a-7604e3a2e6f1.jpg)

**Comment by secretrobotron** [comment]
Here we go. Slightly reduced quality:

![logo-retina](https://cloud.githubusercontent.com/assets/403231/5845428/e860ef7e-a189-11e4-9461-023cb302cb21.jpg)

![logo](https://cloud.githubusercontent.com/assets/403231/5845429/e85e4ad0-a189-11e4-9866-1f714bdc727c.jpg)
