### ISSUE TITLE
onboarding - add limit to 50 characters

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker.org#1116]
probably not essential - 50 characters fill the onboarding thumbnail. add a limit to prevent things from breaking.

**Comment by ScottDowne** [comment]
I just tried 50, but it's still pretty huge...

The final display image can display roughly 22 characters. So right now any experience with more than 22 characters is a bit silly.

For now I'll limit it to 22, and we can see if we want to implement dynamic font size scaling.

I question if our use case really calls for longer phrases vs single catchy words.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/webmaker.org/pull/1125 <- character limit.

**Comment by ScottDowne** [comment]
Fixed, limit is 20 right now, which is roughly the display area in the published preview.
