### ISSUE TITLE
Instructions should disappear after a few letters typed into the field

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker.org#1118]
To keep the interface simple, we only want to show the user what they need to know, when they need to know it.

At the point of typing into the field, users already know what to do, so we can fade out the "What do you love on the web?" instructions and arrow. If possible, we don't want to fade them *right* away, but after a small delay where the user has committed to an action. If the user clicks out of the field or stops typing, we could fade the instructions back in. So that they have it when they need it.

@xmatthewx what do you think?

**Comment by xmatthewx** [comment]
:+1:

**Comment by ScottDowne** [comment]
Question about this.

I am (possibly incorrectly) waiting until the user clicks or the auto input finishes before I show the tooltip.

This would create a case where the dialog never shows up at all.

**Comment by cassiemc** [comment]
Yep, I agree that's wrong. I think the tooltip should show from the very beginning, then hide as described in the first comment. You never know what a user is doing on the page at first load, or what will draw their attention.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/webmaker.org/pull/1129

**Comment by ScottDowne** [comment]
Done
