### ISSUE TITLE
Suggest change for "This page doesn't exist"

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker.org#1131]
I dont think "This page doesn't exist" sounds right.
I sounds like im watching something that doesn't exists.

"Page not found" or "The page you where trying to view does not exists" might be better.

But i havent tried the string in the product so maybe someone else could see what sounds best.

**Comment by secretrobotron** [comment]
@scootergrisen yeah, I see what you mean. Just to be clear, do you mind showing me where you found that string? Take a screenshot, perhaps?

**Comment by scootergrisen** [comment]
On Tranisfex.
I dont know where its being used. Or if.

**Comment by scootergrisen** [comment]
Oh maybe this https://popcorn.webmaker.org/x

**Comment by secretrobotron** [comment]
Ah, I see. That's a good thing to take care of over at https://github.com/mozilla/popcorn.webmaker.org.

It would be good to mirror the 404 page of webmaker.org. e.g. https://webmaker.org/iauwefnliauwnefiawuenf

**Comment by scootergrisen** [comment]
Done
