### ISSUE TITLE
Remove outline on on-boarding experience textbox 

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1134]
When focused, the textbox is highlighted, which looks pretty weird.

![screenshot 2015-01-19 15 30 33](https://cloud.githubusercontent.com/assets/403231/5807327/239fe892-9ff0-11e4-967a-f2d96cace114.png)
 http://stackoverflow.com/questions/3397113/how-to-remove-border-outline-around-text-input-boxes-chrome

**Comment by ScottDowne** [comment]
https://github.com/mozilla/webmaker.org/pull/1135
