### ISSUE TITLE
Start new Optimizely test for on-boarding experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1136]
- [x] turn off old Optimizely test (splash page)
- [x] make a new one that just switches between home-3 and home-6

/cc @HPaulJohnson

**Comment by secretrobotron** [comment]
https://www.optimizely.com/projects/206878104/experiments/2391320382

**Comment by HPaulJohnson** [comment]
/cc @adamlofting 

I will connect with Adam and take the opportunity to setup a new campaign with proper goal setup and non en-US support.

**Comment by secretrobotron** [comment]
Thanks @HPaulJohnson !
