### ISSUE TITLE
ENGAGEMENT: Design review for Privacy Campaign on Webmaker.org 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1138]
**Step 1:** Visit [this url](http://sleepy-ravine-9799.herokuapp.com/en-US/home-3)
**Step 2:** Tinker with the page, specify what elements (on an atomic level) could use polish. Take into account: 
- [ ] desktop: the eyeball in the top right corner: look and feel 
- [ ] desktop: the eyeball in the top right corner animation
- [ ] desktop: the ad block field between the main CTA and values section: look and feel
- [ ] mobile view
- [ ] private eye link: footer look and feel

**Step 3:** File your polish feedback as separate issues within this repo (webmaker) and make sure that I (@iamjessklein) am tagged on the ticket. The ticket title should be prefaced with the word "ENGAGEMENT" like this ticket is. __Put your tickets in the Privacy Day milestone__.

cc/ @thisandagain @cassiemc @gesa  @vazquez @flukeout @xmatthewx 
reference: [QA ticket](https://github.com/MozillaFoundation/plan/issues/246)

**Comment by cassiemc** [comment]
Would clarify some of the 'look and feel' measures:
- [ ] are images svg or generated by code (scalable without loss of resolution)
- [ ] are shape lines and text smooth
- [ ] is spacing elegant and creates good hierarchy
- [ ] usability: is text weight readable
- [ ] usability: is color contrast (on text and shapes) high enough contrast 
- [ ] brand: are colors and typography on brand?

**Comment by iamjessklein** [comment]
:+1:

**Comment by iamjessklein** [comment]
@vazquez and I did a very fine tooth comb overview of the site today and I filed the following tickets:
    * https://github.com/mozilla/webmaker.org/issues/1140
    * https://github.com/mozilla/webmaker.org/issues/1148
    * https://github.com/mozilla/webmaker.org/issues/1149
    * https://github.com/mozilla/webmaker.org/issues/1139 
    * https://github.com/mozilla/webmaker.org/issues/1150
    * https://github.com/mozilla/webmaker.org/issues/1151

**Comment by flukeout** [comment]
Added 
* #1160
* #1161
* #1162
* #1163
* #1164

**Comment by iamjessklein** [comment]
:+1: thanks @flukeout
