### ISSUE TITLE
ENGAGEMENT: add texture to ad field within Webmaker

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1140]
The promo/ad field space looks like it could use a touch of texture to 1. relate to the eyeball and 2. feel less bland. 

![screen shot 2015-01-20 at 1 22 06 pm](https://cloud.githubusercontent.com/assets/535012/5823049/84d733ec-a0a7-11e4-8aa5-1f972ef8c09a.png)

reference: #1138

**Comment by iamjessklein** [comment]
Thinking about these patterns:

![screen shot 2015-01-20 at 2 48 43 pm](https://cloud.githubusercontent.com/assets/535012/5824572/773bee9c-a0b3-11e4-9853-220796207538.png)
or 
![screen shot 2015-01-20 at 2 48 20 pm](https://cloud.githubusercontent.com/assets/535012/5824584/8beb3816-a0b3-11e4-9670-9e90b02c2851.png)

Full context:

![privacysliver-whiteeyepattern](https://cloud.githubusercontent.com/assets/535012/5824595/9c35b0ac-a0b3-11e4-9b3e-b5d4cb1e12ea.png)

Thoughts @cassiemc

**Comment by cassiemc** [comment]
I think this could be cool but would push the pattern more. Something a little less uniform and even more subtle, though I think those light-on-light background colors are on the right track.

Here's some more inspiration:
* Handdrawn could be nice: https://dribbble.com/shots/1747017-wink-wink?list=searches&offset=15
* Would need way less contrast but I like the other shapes along with the eyes: https://dribbble.com/shots/417185-Free-retro-eye-pattern?list=searches&offset=42 
* Content isn't right, but I like the diamond shapes with lines around would could be eyes: https://dribbble.com/shots/1100116-eyescream?list=searches&offset=69

Have a look if you need more: https://dribbble.com/search?page=6&q=eye+pattern

**Comment by iamjessklein** [comment]
[I uploaded some directions on redpen](https://redpen.io/doe3e1d655fc0fe549) - please add feedback there.
