### ISSUE TITLE
ENGAGEMENT: Functional review for Privacy Campaign on Webmaker.org

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker.org#1143]
# Functional Review Checklist for Privacy Day campaign

Go to the follow urls and give a functional review of the Privacy Day campaign! 
* http://sleepy-ravine-9799.herokuapp.com/en-US/home-3
* http://sleepy-ravine-9799.herokuapp.com/en-US/home-6

**Log issues at https://github.com/mozilla/webmaker.org/issues, make sure to use the "Privacy Day" milestone.**

## Functional Testing
- **Cross-browser testing**
  - **Desktop**
    - [x] Chrome (Latest - 2)
    - [x] Firefox (Latest - 2)
    - [x] Internet Explorer (10+)
    - [x] Safari (7+)
  - **Tablet**
    - [x] Safari (7+)
    - [x] Chrome (Latest)
    - [x] Firefox (Latest)
  - **Mobile**
    - [x] Safari (7+)
    - [x] Chrome (Latest)
    - [x] Firefox (Latest)
    - [x] Firefox OS Browser (2.1+)

- [ ] Check layout on common variation of screen resolutions
- [ ] Check all external links are valid

## Experience
- **_/home-3_**
  - **Mobile & Tablet**
    - [Redpen](https://redpen.io/hzfc1693eca3d1ffd0) *note: background color of ad was changed from yellow to grey in [this Redpen](https://redpen.io/vh754f85b1b6bc89fa)*
    - [ ] Text/line spacing is easy-to-read, regardless of viewport size (from 320px +)
    - [ ] Eyeball is smoothly animated
  - **Desktop**
    - [Redpen](https://redpen.io/mb7ff3e5c2effb91d8) *see color note above*
    - [Hover state Redpen](https://redpen.io/mf54aecfeb200cba0d)
    - [ ] Eyeball smoothly follows mouse cursor in supported browsers
    - [ ] Eyeball is static in unsupported browsers, looking straight ahead
    - [ ] Hovering on eyeball flips hexagon to show "Learn more" and link to /private-eye activity
- **_/private-eye (footer only)_**
  - [ ] Footer expands and collapses to be readable and interactive at any viewport
  - [ ] Tapping or clicking "Join Webmaker" launches the join webmaker modal

## Performance
- [x] ~~Check image optimization~~ *(there are no new images)*
- [ ] Check total page/download time
- [ ] Toggle Network pane in Developer Tools (Command + Option + Q). Click on Reload. You will see something that looks like this: https://www.dropbox.com/s/r0fhsppf5bph56t/Screenshot%202014-12-19%2011.46.18.png?dl=0. Keep an eye out for any long-lasting requests or huge image sizes.

## Graphical Objects
- [x] Is the static text clear, concise, and meaningful?
- [x] Are all static text words spelled out (correctly!) and abbreviations used only when space is limited?
- [ ] Is static text capitalized according to Webmaker standards?
- [x] Do buttons follow the Webmaker standards for size and position?

## GUI Operation
- [ ] Are standards followed for mouse and keyboard navigation, manipulation, and interaction (e.g., TAB, SHIFT+TAB, double-click, selection of elements and objects, drag and drop)?
- [ ] Is the cursor changed to indicate when the user tries to take inappropriate action (e.g., hover)?

**Comment by iamjessklein** [comment]
:+1:

**Comment by simonaramkisson** [comment]
Using IPhone 5s and the mobile page works great, easy to read and eyeball is smoothly animated. Hope that helps.

**Comment by secretrobotron** [comment]
Thanks @simonaramkisson

**Comment by ScottDowne** [comment]
Works great for me on chrome and firefox and it's good and responsive.

**Comment by cadecairos** [comment]
Tested using Windows 7.

Firefox 35: looks good, animations good, on high res and low res.
IE9: LOL: https://www.dropbox.com/s/xaooe6arjqizfi2/wmorg_load.png?dl=0
Chrome: Animation flickers when hovered. when on low-res screens, the last animation before the eye "blinks" is not as smooth as on firefox.

**Comment by ScottDowne** [comment]
IE10-11 doesn't have an eye following, everything else is fine in those browsers.
