### ISSUE TITLE
Engagement: Marketing/Copy review for Privacy Day Promo on Webmaker.org

### ISSUE THREAD

**Issue by HPaulJohnson** [mozilla/webmaker.org#1145]
Step 1: Visit: http://sleepy-ravine-9799.herokuapp.com/en-US/home-3

Step 2: Interact with the two new elements on the page, the eyeball rollover and the promotion banner in the middle of the page. Please check for:
 
- Overall messaging appropriateness and effectiveness as part of larger campaign
- Proper spelling, grammar and punctuation
- Proper use of Mozilla Foundation style guide
- Links work and have proper calls to action

Step 3: File your polish feedback as separate issues within this repo (webmaker) and make sure that I am tagged on the ticket. __Put your tickets in the Privacy Day milestone.__

cc/ @edrushka @davesteer @secretrobotron 
reference: QA ticket https://github.com/MozillaFoundation/plan/issues/246

**Comment by iamjessklein** [comment]
:+1:

**Comment by DaveSteer** [comment]
Just QA'd it. Looks good to me.

**Comment by edrushka** [comment]
Looks good to me, too.

**Comment by secretrobotron** [comment]
Thanks all!
