### ISSUE TITLE
ENGAGEMENT: clean up type on flip side of eyeball hover

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1148]
"Privacy Matters" - font weight: 600
    "Learn More" -font weight: 400 
    tighten the spacing in between "Privacy Matters" and "Learn More" by 1px 

cc/ @gesa @vazquez @cassiemc

**Comment by xmatthewx** [comment]
The text feels a bit crowded in the flip-side. Wondering aloud: after it flips, can we animate the hexagon getting larger? If so, text could start smaller so there could be a bit of a margin.

**Comment by iamjessklein** [comment]
fancy talk! 

Well if that can't be done, we are already enlarging the hexagon size by 4px in #1149 

@gesa

**Comment by gesa** [comment]
@xmatthewx I've increased the overall size of the eye by 0.5rem, so that may actually resolve this problem. I hesitate to add any more animations because the last thing we want is more mysterious flickering!

**Comment by iamjessklein** [comment]
@gesa - it looks much better to me. I would say this is good for shipping :shipit:
