### ISSUE TITLE
ENGAGEMENT: clean up styling on "Learn More" button

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1150]
* The Learn More button does not indent when pressed. Take a look at the "Start Creating" CTA and copy its active state CSS.
* The Learn More button is missing the inner-shadow

cc/ @gesa @vazquez @cassiemc

**Comment by gesa** [comment]
@iamjessklein, @flukeout: I can't reproduce this. Which browser were you using? (this button literally uses the exact same code as the "start creating" button above it)

**Comment by gesa** [comment]
False alarm. Figured it out. Fixed.

**Comment by iamjessklein** [comment]
:+1:  woot it looks great.
