### ISSUE TITLE
ENGAGEMENT: design adjustments to grey ad block

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1151]
* Change grey color to match the "Jump Right In" section #ffffff
* Typographic treatment: https://www.dropbox.com/s/28xy0518nsrk6z5/Screenshot%202015-01-21%2010.59.51.png?dl=0

    .home-privacy-day { padding: 4.5rem 0 5rem; }
    .home-privacy-day h2 { margin: 0; }
    .home-privacy-day h4 { margin-top: 1.4rem; }
    .home-privacy-day h4 { font-weight: 400; }
    .home-privacy-day .btn-primary { margin-top: 2rem; }

cc/ @gesa @vazquez @cassiemc

**Comment by gesa** [comment]
@iamjessklein: I made those changes on the desktop viewports, but do you have any feedback on how we should space out mobile views?
![screen shot 2015-01-22 at 14 08 49](https://cloud.githubusercontent.com/assets/782056/5865706/431a6808-a240-11e4-8398-b80eb35ef6cf.png)
