### ISSUE TITLE
ENGAGEMENT: clean up animation in Chrome

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1152]
In Chrome - the flip does in fact look like an error (as @gesa mentioned). If it's not possible to remedy this, it should be replaced with the eyeball animation as seen in mobile. In this case, on click will take you to the activity.

cc/ @vazquez @cassiemc

**Comment by secretrobotron** [comment]
Pretty sure this is a z-fighting issue that works its way back to how textures are splashed onto the screen by the browser's gfx engine. For me, in Chrome, adding `transform: translateZ(2px);` to the svg fixes the problem.

@gesa just depends on where you want to keep the 3D transforms on that set of divs.

**Comment by gesa** [comment]
I'll play with the z translate! the nastiness i was encountering earlier was fix it one place, break it another. but i didn't try that idea yet!

**Comment by iamjessklein** [comment]
:hammer: :wrench:
