### ISSUE TITLE
Weird eyeball flicker in Chrome when hexagon flips.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker.org#1160]
When I hover near enough to the eye for it to start flipping, the eye flickers weirdly.
To reproduce
* put your mouse cursor below they eye
* slowly move up towards eye
* as you get closer observe the eye as it flips
* it flickers weirdly

@iamjessklein

**Comment by iamjessklein** [comment]
@flukeout - which browser are you using?
cc/ @gesa

**Comment by flukeout** [comment]
Mac Chrome version 39

**Comment by iamjessklein** [comment]
ah yeah, thanks for clarifying. Also noted this in #1152
