### ISSUE TITLE
Focused field outline doesn't look nice or stand out on the input field

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker.org#1161]
![image](https://cloud.githubusercontent.com/assets/25212/5846372/eea7905c-a177-11e4-85b1-c76688a9d056.png)

^ maybe remove it or make it a color that stands out more?

@iamjessklein

**Comment by iamjessklein** [comment]
@flukeout that's actually not part of the design that is being shipped. It will be shipped with the #1097 CTA instead.

Closing out this particular comment
