### ISSUE TITLE
Mouse pointer on flipped eye hexagon isn't a "click hand" until you move it again.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker.org#1163]
![image](https://cloud.githubusercontent.com/assets/25212/5846590/a2ef48ba-a179-11e4-9bac-a89841f7ca98.png)

Steps to reproduce
* Mouse mouse to the eye quickly
* It will flip to link, but cursor will remain an arrow
* Cursor only changes to "pointer" when you move your mouse again

Probably the eye whole eye area needs a pointer cursor style, not just the back side.

@iamjessklein

**Comment by iamjessklein** [comment]
good :eyes: catch @flukeout 

Thought's @gesa ?

**Comment by gesa** [comment]
@iamjessklein easy-peasy!
