### ISSUE TITLE
Private Eye page is mostly a ponytail

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1166]
Visiting the Private Eye page on a mobile device (linked from the privacy day webmaker home page), most of the screen is occupied by a ponytail. Should the image be centered?

![screenshot 2015-01-22 13 37 00](https://cloud.githubusercontent.com/assets/403231/5861944/d71f1968-a23b-11e4-8c75-77038fe93286.png)

**Comment by secretrobotron** [comment]
Relates to #1143

**Comment by gesa** [comment]
hahaha that is originally out of scope, but I will ABSOLUTELY fix that. kind of a funny oversight. ^_^

**Comment by iamjessklein** [comment]
I love this. :haircut:  :+1: @secretrobotron
