### ISSUE TITLE
Text shows through eye in Safari

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1169]
Moving the mouse over the eye quickly in Safari causes [backwards] text to show through. ![screenshot 2015-01-22 14 24 06](https://cloud.githubusercontent.com/assets/403231/5862780/7fe6589e-a242-11e4-8dba-8af195c0bc22.png)

My guess: same problem as #1152, but good to verify.

**Comment by gesa** [comment]
I'm actually really impressed you managed to get a screen grab of that because I can only get it to show for like a quarter of a second. :clap:

**Comment by gesa** [comment]
OH MY GOSH AND IT WORKS ON SAFARI 7 TOO YISSSSSSS

cc @iamjessklein

**Comment by iamjessklein** [comment]
ahhh! confirmed! 
:+1:  :dancer: :dancers: :facepunch: :v:
