### ISSUE TITLE
Finalize copy for MOI splash page for MWC 

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker.org#1170]
Copy is here: https://docs.google.com/a/mozillafoundation.org/document/d/1oo8vCNZDzvdhE8OU0P26oVy7xFCYo8widXIWLrircbM/edit

@edrushka @benrito @HPaulJohnson @ davidascher have all signed off, so this copy is final.

**Comment by sabrinang** [comment]
Updated website copy (seen on design redpens): https://docs.google.com/a/mozilla.com/document/d/1d2ET2yBrM0C_ObUPyhqkjTWAKgbzjd7UGP8tMhslKsc/edit?usp=sharing

**Comment by sabrinang** [comment]
Copy feedback on "Partner with Mozilla" section: https://redpen.io/sveed4aec568a4488a#showing-comment-822581

**Comment by edrushka** [comment]
@HPaulJohnson please review that copy ^ and let me know if it needs tweaking.

**Comment by HPaulJohnson** [comment]
Done. Cassie's suggestion to swap the order of the 2nd and 3rd sentence makes it much more clear. Let's do that.

**Comment by edrushka** [comment]
Thanks. I've made this change in the final copy doc: https://docs.google.com/a/mozilla.com/document/d/1d2ET2yBrM0C_ObUPyhqkjTWAKgbzjd7UGP8tMhslKsc/edit?usp=sharing

@mmmavis This is the doc you should use for building the site.
