### ISSUE TITLE
Wide-screen privacy day splash screen is shown on Android tablet

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1172]
Firefox on Android tablet shows the screen you're supposed to see on desktops (with the eye in the top-right). In landscape mode.

(Tried to take a screenshot, but couldn't get it over here.)

**Comment by gesa** [comment]
@secretrobotron Could you get me the viewport width of that particular tablet? I'm gonna have to think long and hard about what the UL of "tablet" viewports is, and try to make decisions about edge cases there.

**Comment by secretrobotron** [comment]
I don't... actually understand... how to use one of these tablets to get any debugging information.

Regardless, I just tried in the device emulator in Chrome. Emulating Galaxy Tab 7+:

![screenshot 2015-01-23 13 34 46](https://cloud.githubusercontent.com/assets/403231/5880232/ac56a51a-a304-11e4-95ff-9782276967cb.png)

**Comment by gesa** [comment]
Thanks to a PR by @ScottDowne, this is no longer an issue. If the page doesn't detect a mouse moving, the css animation will start up.
