### ISSUE TITLE
Collect links for MOI splash page for MWC

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker.org#1174]
We need all the links indicated in the google doc: https://docs.google.com/a/mozillafoundation.org/document/d/1oo8vCNZDzvdhE8OU0P26oVy7xFCYo8widXIWLrircbM/edit?pli=1

This blocks the build #1168

**Comment by edrushka** [comment]
cc @sabrinang @mmmavis

**Comment by mmmavis** [comment]
We are still missing link to the Webmaker India research report.  Can someone forward me the link? Thanks!

**Comment by edrushka** [comment]
@LauraReynal ETA?

**Comment by thisandagain** [comment]
@edrushka Will have by EOD Friday. Link will be `http://mzl.la/india`

**Comment by mmmavis** [comment]
@thisandagain sorry, forgot to mention link to "A Locally Relevant Web: Early Research & Recommendations" as well.

**Comment by thisandagain** [comment]
@mmmavis Let's use `http://mzl.la/research` for that.

**Comment by mmmavis** [comment]
Thanks, I just added those in the build :smiley:

**Comment by mmmavis** [comment]
Links have been added to the build. :+1:
