### ISSUE TITLE
Collect partner icons for MOI splash page for MWC

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker.org#1175]
Need icons for the partners you want featured: 

Mozilla • GSMA [link and logo]
Telefonica[link and logo]
Grameenphone (unconfirmed)[link and logo]
Equity Bank[link and logo]
Econet Wireless (unconfirmed)[link and logo]
a2i Programme, Prime Minister’s Office Bangladesh[link and logo]
Bill & Melinda Gates Foundation (unconfirmed)[link and logo]
UNESCO[link and logo]
Souktel[link and logo]
Praekelt[link and logo]
StudioD[link and logo]

I pulled ^ from this doc: https://docs.google.com/a/mozillafoundation.org/document/d/1oo8vCNZDzvdhE8OU0P26oVy7xFCYo8widXIWLrircbM/edit?pli=1

**Comment by edrushka** [comment]
This blocks design #1167 and build  #1168

**Comment by edrushka** [comment]
cc @sabrinang

**Comment by mmmavis** [comment]
Copying @benrito 's comment from https://github.com/mozilla/webmaker.org/issues/1205#issuecomment-76023749
> Hey guys, here is our pre-MWC logo clearance:

> https://dl.dropboxusercontent.com/u/8176339/MWC%20logo%20clearance.zip

> Each folder has the high res file and the URL to link.

> Feel free to crop the A2I logo so it's pretty.

> At this stage we have 6 logos that are carefully selected to tell a story. There are some politics here so placement matters.

> I've included "layout.png" to suggest how we might stage them. My preference is to have them in one row, though I know the present design is 5 per row.

> Next heartbeat or the one after, we may want to update these.

**Comment by mmmavis** [comment]
@benrito fyi, linking to www.m4dimpact.com via **https** throws out security warning.  I will use http://www.m4dimpact.com/ instead.

**Comment by mmmavis** [comment]
Live on https://moi-splash.herokuapp.com/localweb :dancers:

**Comment by mmmavis** [comment]
And I did crop the A2I logo a bit.

**Comment by mmmavis** [comment]
[Build](http://webmaker.org/localweb) is done.  If anything needs to be changed please file a new ticket.
