### ISSUE TITLE
Fix broken links on Made with Code pages

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/webmaker.org#1178]
@secretrobotron Thank you!

We created pages for three Thimble projects that are featured on Google's Made with Code site, and they all have broken links.

On each, there is a large "remix" button in the middle of the page that is broken. However the "remix" buttons on the left side of the page are all currently linking to the correct Thimble projects.

![screen shot 2015-01-23 at 5 27 12 pm](https://cloud.githubusercontent.com/assets/4885898/5883940/23f5923c-a325-11e4-89e0-f6668be0ab19.png)

The broken links end up looking like this: 
![2_errors](https://cloud.githubusercontent.com/assets/4885898/5883956/4e2db156-a325-11e4-877f-0d5d6fa0f92a.jpeg)

* The big "Remix" button on the meme page https://webmaker.org/en-US/madewithcode-meme should link here: https://thimble.webmaker.org/project/60766/remix
* The big "Remix" button on the online poster page https://webmaker.org/en-US/madewithcode-poster should link here: https://thimble.webmaker.org/project/60767/remix
* The big "Remix" button on the first webpage page https://webmaker.org/en-US/madewithcode-firstwebpage should link here: https://thimble.webmaker.org/project/60764/remix

Let me know if you need any more info, and when they're fixed so I can let Google folks know (they brought it to my attention).

**Comment by gesa** [comment]
Closing this because #1178 fixed it and it's on prod (I tested and verified.)

**Comment by ldecoursy** [comment]
Thanks a million @gesa and @secretrobotron!
