### ISSUE TITLE
ENGAGEMENT: in Chrome on tablet checkbox mark is crooked

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/webmaker.org#1181]
Doing the functional review #1143 I noticed that in Chrome on tablet, everything looks great except that the checkbox mark - coming off of the Private Eye Activity -  looks a bit funky: 

![-1](https://cloud.githubusercontent.com/assets/535012/5904877/d9ed97d4-a559-11e4-8bd4-72450f8b3b24.jpg)

cc/ @gesa @secretrobotron

**Comment by gesa** [comment]
This is a Login bug and out of scope for Privacy Day. It's been addressed in mozilla/webmaker-login-ux#154.
