### ISSUE TITLE
Create goggles setup page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1186]
- [ ] style and build of page in image below
- [ ] X-ray Goggles Button
- [ ] Link to Try Goggles goes to landing page
- [ ] Display appropriate video (sniff platform; to be hosted on youtube; created in https://github.com/mozilla/goggles.webmaker.org/issues/158)

![screenshot 2015-01-27 14 54 19](https://cloud.githubusercontent.com/assets/403231/5925831/697f67ee-a634-11e4-9cef-d35a34c41827.png)

**Comment by Pomax** [comment]
not seeing the "Try goggles" link on this mockup?
