### ISSUE TITLE
Add GA event to home-6 to see what words people enter

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1187]
@adamlofting would you be able to help me do this tomorrow? Still don't think I can use GA (but I'll check).

**Comment by adamlofting** [comment]
Sure, this would be done using our [webmaker-analytics](https://github.com/adamlofting/webmaker-analytics) module.
1. The module is already part of the webmaker.org project, but we need to make sure the angular/require-style loading makes this available when we record the event.
2. It makes most sense to record this when the "published" version is displayed back to the user.
3. At that point we fire an analytics event such as `analytics.event("Onboarding (I heart...) clicked Next", {label: "I heart: " + sanitizedUserContentVariableHere });`

**Comment by adamlofting** [comment]
@secretrobotron let me know if you'd like help implementing or just with the spec? (it's a pretty small dev task and I'm happy to help).

**Comment by secretrobotron** [comment]
We just disabled access to home-6. Closing this ticket!
