### ISSUE TITLE
Re-visiting home page avoids optimizely router

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1189]
1. Visit webmaker.org (you should be redirected to something like https://webmaker.org/en-US/home-3)
2. Click on the Tools tab to visit the tools page.
3. Click on webmaker logo again to go back to the home page.

You'll now be on the home page without touching the optimizely router, and so never shown home-3 or home-6 as intended.

**Comment by secretrobotron** [comment]
Probable solution: eliminate home, home-2, home-4, and home-5, and make home-3 default for now.

**Comment by gesa** [comment]
Closed by #1190
