### ISSUE TITLE
Localize MOI splash page for MWC

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker.org#1205]
The Mobile Opportunity Splash page should be localized into Bangla and Brazilian Portuguese in time for Mobile World Congress (March 2).

The page is almost through design (#1167) and the build will start on Feb 4 (#1168).

@alicoding can you please:
a) advise us on making sure the page is localizable, and
b) once the mechanics are in place and the copy is final, localize

We need excellent quality translation, so we can pay for Transifex premium to get high quality, unless you can recommend contributors we know and trust.
cc @benrito @HPaulJohnson @davidascher @sabrinang @mmmavis

**Comment by alicoding** [comment]
Quick question... Which Bengali we want this to be translated into? Indian or Bangladesh or both? Transifex doesn't offer paid translation for bangla but I can probably ask the Indian community to see if they can help otherwise we can find another solution here

**Comment by edrushka** [comment]
Hmmm...I don't know. @benrito @davidascher ??

**Comment by davidascher** [comment]
Bangla would be more powerful if we can get it.  In general, it's a high priority language for us.  Maybe @LauraReynal can help us connect w/ potential localizers.

**Comment by LauraReynal** [comment]
ok on it

**Comment by LauraReynal** [comment]
@edrushka @alicoding I cced you on a email to ask Help from the Bangladeshi community. 
I know more people but unsure of the english level, and also unsure how you want this work to be organized, so I will let you bounce on my email and do as you prefer :smile: Thanks !

**Comment by LauraReynal** [comment]
ok the team is on-board :smile: I'll let you give instructions to Zak on the email thread. 
Let me know if you need more help. 
Thanks !

**Comment by edrushka** [comment]
@alicoding Thanks for emailing. What do you need from me to kick things off with Zak?

**Comment by benrito** [comment]
Ali, could we do Hindi as well?

**Comment by alicoding** [comment]
Hey @edrushka! I guess right now what we need here is to get the resource file/copy up on Transifex if that is not done and then we can ask the team to help us start doing the translation there.

**Comment by alicoding** [comment]
@benrito We do have Hindi localizers, so I think this is doable if it is not too big and they have enough time to do the translation.

**Comment by alicoding** [comment]
I think it is fine as long as we have enough time for translators to do the translation.

**Comment by edrushka** [comment]
If the site needs to be translated (and reviewed) by March 1, can you please give me a deadline for when you need the file, Ali? Thanks.

**Comment by alicoding** [comment]
It is hard to say when I don't know exactly how much content we have and the capacity of our translators. I guess the question here is really depend on the content to be exact.

**Comment by davidascher** [comment]
@alicoding something like https://redpen.io/yd8271fea5b795309d

**Comment by alicoding** [comment]
If we get the file next week and have at least one week for translators and one week for QA I think it might be doable. 



On Monday Feb 2, 2015 at 7:07 PM, David Ascher <notifications@github.com>, wrote:

@alicoding something like https://redpen.io/yd8271fea5b795309d

---

**Comment by mmmavis** [comment]
Hey @alicoding ,

The copy is locked and at this point we are just missing

1. final partner logos (I guess we don't have to translate partner names in the `<img>` ` alt` attribute?)
2. links to things that aren’t ready yet, but will be before MWC
3. a link to one partner

I believe the things mentioned above shouldn't block us from starting translating the copy.  If that true, how would you like the .json file to be formatted?

**Comment by alicoding** [comment]
key:value or Chrome-i18n format either one is fine, but if the strings got some complicated or missing context then we should use Chrome-i18n and then add description to the string that needs explanation.

``` json
{
  key: {
      "message": "value",
      "description": "This is a description to the value string"
    }
}
```

**Comment by mmmavis** [comment]
Cool!  I'll have the file ready by EOD.

**Comment by mmmavis** [comment]
Hey @alicoding
Wondering if I can just check in the .json file to my branch... it's currently being gitignored(on purpose?)

Anyways here's the [json file](https://gist.github.com/mmmavis/ab1f1b7bcfccbc3ee521).

There are few things that I didn't include in the file:
- Localized language text, eg. español, বাংলা
- Partner names
- Quotes (last section on the [mockup](https://redpen.io/sveed4aec568a4488a))
- Site title (site meta)
  - Does this need to be localized?
  - @edrushka I need copy for this.  This is the title that you see on your browser tab & thumbnail displayed when you share this page on social media.
- Site description (site meta)
 - Does this need to be localized?
 - @edrushka I need copy for this.  This is the description that you see in the thumbnail when you share this page on social media.

**Comment by alicoding** [comment]
I forgot to ask. How are you doing the localization here since it is static page as you mentioned?

**Comment by alicoding** [comment]
And also @mmmavis you have to force add file to be able to have that on your branch. It is intentional.

**Comment by mmmavis** [comment]
@alicoding ,

k, `localweb.json` has been added to my branch.

Maybe static page wasn't a right word to refer to it.  What I meant was that page doesn't have to be use any of the login logic or Angular etc.  I'm still using `{{ gettext("key here") }}` to grab the text (seen in my WIP [localweb.hml](https://github.com/mmmavis/webmaker.org/blob/moi-landing-page/views/localweb.html))

**Comment by edrushka** [comment]
@alicoding Do you think it's possible to have the localization done by March 1? Let me know if there are any blockers.

**Comment by alicoding** [comment]
@ednapiranha The **translation** at this point if we upload them **now** and then give our translators enough them it might be possible to have it done by March 1st. We have to keep in mind about one thing which is the Bengali (Bangladesh team) they are pretty slow in translation right now, but we might have to ask people who @LauraReynal introduce to see if they can help us get this done soon.

@edrushka so that email thread about the translation you might want to send them an email once I have the file uploaded on Transifex.

**Comment by mmmavis** [comment]
@alicoding : is it okay if we are still missing 1-2 strings?

**Comment by alicoding** [comment]
@mmmavis better upload it sooner so people can start translating it. I would like a final copy that we are sure about by EOD (EST if possible) otherwise email me and I will upload it for you if you don't know the process.

**Comment by alicoding** [comment]
@ednapiranha so two requests from you.

1. Write an announcement for Transifex community to help us translate (if we want more than one language otherwise please list me what language we are targeting and I will manually send them to each language team and ask them to help us)

2. Send an email to that thread where @LauraReynal introduced us to the Bengali community so that they are aware of this new file and will be able to get this done before March 1st.

**Comment by mmmavis** [comment]
@alicoding: there are 2 strings that are still waiting to be finalized (site title and descriptions).  For point 1 - 3 in my previous [comment](https://github.com/mozilla/webmaker.org/issues/1205#issuecomment-74025286) I just want to make sure that those do NOT have to be localized.

I think I have admin power to https://www.transifex.com/projects/p/webmaker/ but I'm not sure how to upload file there.  Pointers?

**Comment by alicoding** [comment]
@mmmavis you just need to go to *resources* tab then click upload new file and select the type which is `Chrome-i18n` in your case.

**Comment by alicoding** [comment]
@mmmavis I would say those two needs to be localized since it will be display on Google as well.

**Comment by mmmavis** [comment]
@alicoding https://www.transifex.com/projects/p/webmaker/resource/localwebjson/ I hope I did this right.

**Comment by alicoding** [comment]
@mmmavis looking good to me! now if we want to make sure we have the translation ready for certain time I would say we make an announcement and ask people to help translate and point them to the link here @mmmavis https://www.transifex.com/projects/p/webmaker/resource/localweb/

**Comment by mmmavis** [comment]
Hey @alicoding , how do we make an announcement?

**Comment by alicoding** [comment]
@mmmavis https://www.transifex.com/projects/p/webmaker/announcements/ :)

![screen shot 2015-02-16 at 10 02 15 pm](https://cloud.githubusercontent.com/assets/4368149/6222739/86ad3e92-b627-11e4-83dc-7ddf54df39c9.png)

**Comment by edrushka** [comment]
@alicoding process-wise does it make more sense for you to do the announcement? Also, just re-iterating that we can (and should) pay for Pro services on this. The quality of translation must be excellent.

**Comment by alicoding** [comment]
@edrushka I could do that for you if you have the copy for me. As I have mention previously for Bengali Transifex does not provide paid translation, and we have to rely on our contributors. Otherwise we will have to find another service just for the translation for this ticket.

**Comment by edrushka** [comment]
@alicoding How about this for the copy:

Hi,
As part our presence at Mobile World Congress, we’re launching a new page to showcase Webmaker’s mobile opportunities. Here it is on staging: https://moi-splash.herokuapp.com/localweb
We’d like to have this site localized into Brazilian Portuguese, and Hindi and Bangla.
Can you help us?
The resource file can be found here [link]
If you need more context for any string, or need a screenshot to see it on the page, please comment. 
Thanks for your help!
Ali 
@mmmavis @davidascher are there any objections to showing the link on staging?

**Comment by edrushka** [comment]
As for the paid translation, let's do that for whatever languages we can, and rely on our contributors for Bangla.

**Comment by alicoding** [comment]
@edrushka I will do the announcement after I get +1 from either @mmmavis and/or @davidascher.

As for part on paid translation. Do we want to wait for a week or just do the paid translation right away?

**Comment by edrushka** [comment]
I think the goal for paid translation = high quality translation. I don't know enough about Transifex to know if we can get excellent quality through the unpaid service.

**Comment by alicoding** [comment]
@edrushka unpaid service is just mean our contributors and by far they are no complain about their translation except it can be slow sometimes.

**Comment by davidascher** [comment]
No objection to showing the link on staging.

Copy is fine by me.

Paying and getting this done ASAP are both good ideas IMO.

**Comment by edrushka** [comment]
Thanks David.
@alicoding let's get this going on the paid service ASAP. No need to wait.

You can tweak the copy I provided above to only ask for Bangla from the volunteer localizers. Have you connected with @LauraReynal about her specific contacts?

**Comment by alicoding** [comment]
So far without having to use the paid service we already have this done @davidascher @edrushka 

* Polish (Poland) 100%
* Spanish 100%
* Finnish 100%
* Dutch 100%
* Danish (Denmark) 100%
* Portuguese (Brazil) 97%
* Albanian 97%
* Hindi (India) 97%
* Chinese (China) 89%
* Bengali 71%

I'm going to do three things here. 

[] Send an email to the Bengali (Bangladesh) team that introduced by @LauraReynal  to ask them to help
[] Send an announcement to the whole Transifex community to get more translation done for this resource file
[] Use paid service if the list of language we want is not completed by tomorrow end of day.

How is that sound?

**Comment by davidascher** [comment]
Sounds good to me!

**Comment by edrushka** [comment]
Awesome, Ali! Thank you!

**Comment by alicoding** [comment]
@mmmavis @edrushka can we do string freeze on localweb copy now? we don't have enough time if we still updating or changing strings in the file and our translators going to get burn out if we update this too frequently.

**Comment by mmmavis** [comment]
I'm done with adding all the copy tweaks in the build/Transifex.  @edrushka , is there anything else that need to be adjusted? (bolding text and adding links could count too)

**Comment by edrushka** [comment]
@benrito @HPaulJohnson can we freeze copy as per Ali's concern about translator burnout?

**Comment by HPaulJohnson** [comment]
@edrushka no more changes that i know of so good to freeze now.

**Comment by benrito** [comment]
Think yes.

**Comment by benrito** [comment]
Hey guys, here is our pre-MWC logo clearance:

https://dl.dropboxusercontent.com/u/8176339/MWC%20logo%20clearance.zip

Each folder has the high res file and the URL to link.

Feel free to crop the A2I logo so it's pretty.

At this stage we have 6 logos that are carefully selected to tell a story. There are some politics here so placement matters.

I've included "layout.png" to suggest how we might stage them. My preference is to have them in one row, though I know the present design is 5 per row.

Next heartbeat or the one after, we may want to update these.

**Comment by edrushka** [comment]
Great. Thanks, Ben. @mmmavis can you try these in one row and see if it looks ok?

**Comment by mmmavis** [comment]
Alrighty, let's continue the convo for logos here instead: https://github.com/mozilla/webmaker.org/issues/1175 :smile:

**Comment by alicoding** [comment]
I'm closing this since it is localized and we are showing it off live!

**Comment by edrushka** [comment]
Thanks for all your help on this, @alicoding! I can't believe how many languages we got up in so little time.
