### ISSUE TITLE
Enable da_DK on all webmaker site

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker.org#1209]
Danish (Denmark) is fully translated and reviewed and our contributor did some QA and believe it is ready to go on production.

We should do one last round of QA and enable this on all site.

https://webmaker.mofostaging.net/da-DK

**Comment by alicoding** [comment]
CC @scootergrisen

**Comment by alicoding** [comment]
@jdotpz can we add `da-DK` in the list of supported language in the prod.env ? for Webmaker first at least so we can try it out on production to see if everything is okay then the rest of the app?

**Comment by jdotpz** [comment]
@alicoding so to be specific, we'll add the following to the env:

*WAS*
export SUPPORTED_LANGS='[ "bn-BD", "bn-IN", "de", "en-CA", "en-US", "es", "es-CL", "es-MX", "fr",  "hi-IN", "id", "it", "km", "nl", "pt", "pt-BR", "ru", "sl", "te", "th-TH", "zh-CN",  "zh-TW" ]'

*WILL BE*
export SUPPORTED_LANGS='[ "bn-BD", "bn-IN", "da-DK", "de", "en-CA", "en-US", "es", "es-CL", "es-MX", "fr",  "hi-IN", "id", "it", "km", "nl", "pt", "pt-BR", "ru", "sl", "te", "th-TH", "zh-CN",  "zh-TW" ]'

When you +1, I'll add this to our configs and push that out.

**Comment by alicoding** [comment]
+1 @jdotpz ! :D

**Comment by jdotpz** [comment]
The kick just went out, should be ~1 minute.

**Comment by scootergrisen** [comment]
Yeah! https://webmaker.org/da-DK :heart_eyes_cat:

**Comment by alicoding** [comment]
Thanks @jdotpz <3
