### ISSUE TITLE
"Process" link is broken on build.webmaker.org

### ISSUE THREAD

**Issue by OpenMatt** [mozilla/webmaker.org#1221]
@davidascher looks like its maybe a https issue?

**Comment by OpenMatt** [comment]
Can we also shorten "design assets" to just "design?"

**Comment by davidascher** [comment]
wilco

**Comment by davidascher** [comment]
closed #1221

(matt: fyi, in the future, build.webmaker.org bugs should be filed on
https://github.com/mozilla/build.webmaker.org/issues/)
