### ISSUE TITLE
Add i18n to goggles landing page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1223]
`goggles.html` needs some `gettext` or `i18n` filtering so that the transifex community can localize asap.

Could probably use a separate `goggles.json` in `/locale/en_US/`.

**Comment by alicoding** [comment]
@secretrobotron is this the one we talked about in the office last week?

**Comment by secretrobotron** [comment]
@Pomax @alicoding yep! Don't worry. Fixed by a patch I wrote.
