### ISSUE TITLE
Possible log-in related bug on webmaker.org badges pages

### ISSUE THREAD

**Issue by OpenMatt** [mozilla/webmaker.org#1229]
* NOTE: @smithisgeneric (Karen Smith) reports a possible bug with webmaker.org badges pages like this one:
https://webmaker.org/badges/hive-community-member

"I am having trouble clicking on the "Login to apply" green button, through to the 'claims' page. Is this because of login changes to Webmaker?"

**Comment by ScottDowne** [comment]
Likely fixed in #1237 

Try it now, reopen if still broken.
