### ISSUE TITLE
Privacy Eye wonky in FFv35

### ISSUE THREAD

**Issue by Melechuga** [mozilla/webmaker.org#1231]
When the privacy eye on the landing page is following the mouse, the white circle shifts down and runs into the "box" at the bottom of the hexagon. When it's just floating, however, it's fine.

**Comment by Melechuga** [comment]
Attaching screenshot:

![screen shot 2015-02-12 at 2 15 26 pm](https://cloud.githubusercontent.com/assets/5815317/6178274/1dd35270-b2c2-11e4-9bd4-6e5086367a69.png)

**Comment by ScottDowne** [comment]
Hm, I'm not able to reproduce with ff 35.0.1 maybe it was fixed?
