### ISSUE TITLE
It's impossible to apply for a badge

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1232]
STR:

* go to https://webmaker.org/badges/design-maker
* notice the `login to apply` button.  Click on it. Nothing happens.
* Oh well, you figure, I'll just "sign in", maybe that's the same as "log in".
* Click on login (i have other bugs to file on that flow).  
* Do the login dance, get in

Actual: The apply button is missing (except if you're an admin, which is funny).
Desired: **Authed users should see the apply button on badge details pages.**

**Comment by ScottDowne** [comment]
Best I can tell, that button never got a click event setup for it.

**Comment by ScottDowne** [comment]
Fixed in #1237
