### ISSUE TITLE
localweb images should be shrunk

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1242]
In particular, there's currently a link to https://moi-splash.herokuapp.com/img/moi/creativity.jpg which is a _huge_ image.  It should be resized to fit the max size it'll ever be displayed at.

**Comment by mmmavis** [comment]
Oh yea that one def needs to be resized.  I'll check to see if there are any other images that I forgot to process.

**Comment by mmmavis** [comment]
i think this is done.
