### ISSUE TITLE
The CTA is in (IMO) too large a type when seen on a phone

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1243]
![2015-02-17 01 24 48](https://cloud.githubusercontent.com/assets/51278/6221973/ca81c48e-b600-11e4-9568-cdce35f5c9b8.png)

**Comment by mmmavis** [comment]
@sabrinang let's do style tweaking together tomorrow.

**Comment by mmmavis** [comment]
fixed.
