### ISSUE TITLE
Footer layout on a mobile device is too tall

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1244]
![2015-02-17 01 26 10](https://cloud.githubusercontent.com/assets/51278/6221986/f4c2bc6c-b600-11e4-93b8-eaaeee9446c7.png)

**Comment by mmmavis** [comment]
@sabrinang @cassiemc : I'm following what https://webmaker.org/ is using.  But maybe we can do some adjustment for this MOI splash page only.

Staging: https://moi-splash.herokuapp.com/localweb

**Comment by sabrinang** [comment]
we could follow the mobile [redpen] (https://redpen.io/wjc1c9851c3fd2c80a) and split it into two columns so its vertically shorter: ![screen shot 2015-02-16 at 6 48 50 pm](https://cloud.githubusercontent.com/assets/2492510/6222655/8130d82c-b60c-11e4-98d1-b39e6ec15cad.png)

**Comment by cassiemc** [comment]
+1 @sabrinang

**Comment by mmmavis** [comment]
Cool, do we want to include the "Teach" link as well? @sabrinang
