### ISSUE TITLE
Login to apply button doesn't work on badge pages

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker.org#1249]
e.g. on https://webmaker.org/badges/webmaker-super-mentor

Click "Login to Apply"

Nothing happens

![image](https://cloud.githubusercontent.com/assets/1455535/6237979/538a69f6-b6c5-11e4-8fa9-39c04bbe0730.png)

**Comment by ScottDowne** [comment]
https://github.com/mozilla/webmaker.org/pull/1237

Fixed.
