### ISSUE TITLE
Track clicks to 'download' from App Beta Install Page

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker.org#1253]
Re: https://github.com/MozillaFoundation/plan/issues/81

When a user clicks to download the app, Google Analytics will not by default record that anything has happened. We need to fire a custom tracking event to record actions that take the user to external URLs, or to file downloads.

#### To track clicks to download we should:

* [x] Include/require the [webmaker-analytics module](https://github.com/mozilla/webmaker-analytics) on the page.
  * This module is [already](https://github.com/mozilla/webmaker.org/blob/master/bower.json#L23) part of webmaker.org
* [x] Wire up an on click event for the download button to fire: `analytics.event("Download Beta App");`
* [x] Make sure the page has time to record the event before redirecting the user.
  * Either with a delay, or by opening the link in a new tab

If there are separate links to different OSs we can use a label to distinguish:
e.g.  `analytics.event("Download Beta App", {label: "Android"});`

**Comment by cadecairos** [comment]
> If there are separate links to different OSs we can use a label to distinguish

The platform detection will be happening on the install page, so I guess we can add events there to detect that?

**Comment by cadecairos** [comment]
> Make sure the page has time to record the event before redirecting the user.
> 
>     Either with a delay, or by opening the link in a new tab

any idea how much time is needed?

@thisandagain would it be okay to open a new tab if we don't want to use a setTimeout

**Comment by thisandagain** [comment]
Ok to target `_blank`. This is one of those places where callbacks for GA tracking would be helpful. :smiley:

**Comment by cadecairos** [comment]
> This is one of those places where callbacks for GA tracking would be helpful

:+1:

**Comment by adamlofting** [comment]
One extra point to clarify.

This tracking specified above for the download button is assuming this is on a page that already has our basic GA tags in it. If we're building this on the back of webmaker.org, that code should already exist, like the partner version of this page which Mavis has been building: https://github.com/mozilla/webmaker.org/pull/1246/files#diff-53e7b880baac8b7ce4e31135ba192831R481

@cadecairos does that make sense?

**Comment by adamlofting** [comment]
> The platform detection will be happening on the install page, so I guess we can add events there to detect that?

That's a good point. I'll dig out that ticket and see what tracking we can add to those pages. No action on that is required in this ticket though.

**Comment by thisandagain** [comment]
https://github.com/mozilla/webmaker-app/issues/633

**Comment by adamlofting** [comment]
Closed in https://github.com/mozilla/webmaker.org/issues/1277
