### ISSUE TITLE
Track links to non-webpage URLs in MOI Splash Page

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker.org#1254]
Re: https://github.com/mozilla/webmaker.org/issues/1168

When a user clicks to non-webpage URLs, Google Analytics will not by default record that anything has happened. We need to fire a custom tracking event to record actions that take the user to external URLs, or to file downloads.

#### To track clicks to download we should:

* [x] Include/require the [webmaker-analytics module](https://github.com/mozilla/webmaker-analytics) on the page.
  * This module is [already](https://github.com/mozilla/webmaker.org/blob/master/bower.json#L23) part of webmaker.org
* [x] Wire up an on click event for each of the links we want to track like this: `analytics.event("Download Beta App");`
* [x] Make sure the page has time to record the event before redirecting the user.
  * Either with a delay, or by opening the link in a new tab

#### Things we should track:
* `analytics.event("Click on Partner with Us");`
* `analytics.event("Try the Open Beta");`
* `analytics.event("Play Video", {label: "MOI Partner Opportunity"});`
* `analytics.event("Download Report", {label: "___REPORT_NAME_HERE___"});`

**Comment by mmmavis** [comment]
review for me @adamlofting :smile: ? see [PR](https://github.com/mmmavis/webmaker.org/pull/2)

**Comment by adamlofting** [comment]
@mmmavis this looks great. I just had a few comments inline. 
Then if we can merge this and get it onto staging we can do a final QA to check the data is coming through to GA.

**Comment by mmmavis** [comment]
@adamlofting 
Live on https://moi-splash.herokuapp.com/localweb :dancer:  Note that this is just a Heroku app that I set up, not sure if we have an official staging webmaker.org site somewhere.  Hopefully this is enough for testing.

**Comment by adamlofting** [comment]
:+1: 

CC'ing @secretrobotron to show you how the webmaker staging works, as we'll want to get this onto webmaker.mofostaging.net so that we can check this data is arriving in GA.

**Comment by secretrobotron** [comment]
@mmmavis yeah! You've just got to tag the webmaker.org repo and push that up to mozilla/master. Happy to show you how. Ping me when you're around :).

**Comment by mmmavis** [comment]
@adamlofting https://webmaker.org/localweb is up :dancers: :dancers: :dancers: :dancers: :dancers:

**Comment by adamlofting** [comment]
Perfect! This data is now arriving in GA :hatching_chick: :hatched_chick: 
![screen shot 2015-02-27 at 05 40 27](https://cloud.githubusercontent.com/assets/1901816/6411107/41a606e8-be43-11e4-9b70-87bfdafbc3a6.png)
