### ISSUE TITLE
Can't view the front page when logged in

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker.org#1255]
Go to https://webmaker.org/ without being logged in and you see the front page.
Log in and then visit the same URL redirects to https://webmaker.org/en-US/explore so i can't see the front page when i'm logged in. Only when i'm logged out.

**Comment by thisandagain** [comment]
We direct all logged-in users to /explore as the splash page is focused on getting users to sign-up.

**Comment by scootergrisen** [comment]
I dont like that.
Why should i be "blocked" from viewing a certain page if that if the page i want to view.
Also its confusing that the same link take me to different places depending on if im logging in or not.
Plus when localising the page its not good that i have to logout to check a string or something.
