### ISSUE TITLE
Implement mobile install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1257]
Blocks #1260
Blocks #1262
Blocks #1273

**Comment by cadecairos** [comment]
I'm curious what kind of tech stack we want to build this with.

Since the code will live in this app, we've got to decide between:

1. A new view that's handled by the angular router 
2. A new view served by express routing

Personally, 2 seems like the better way, especially if this page is going to be getting a lot of traffic, and Angular might have a negative performance hit on mobile.

Also, do we want to build using React? that would mean adding a whole set of new dependencies and a new build pipeline (jsx > js > babel > browserify > uglify)

thoughts? @secretrobotron @jbuck @thisandagain @davidascher

**Comment by secretrobotron** [comment]
- Good call on using express, but only if there's already some server component to webmaker app that serves web pages.
- I think it's not angular, but Vue. Might change your thinking.
- My guess is we want to steer clear of react for the time being.

cc'ing @k88hudson here for thoughts.

**Comment by thisandagain** [comment]
:+1: on using express. I don't see why we would use a client-side framework (either React or Angular) for a pretty straightforward / static page.

**Comment by cadecairos** [comment]
> Good call on using express, but only if there's already some server component to webmaker app that serves web pages.
> I think it's not angular, but Vue. Might change your thinking.

what part of this ticket involves work on webmaker-app? 

> I don't see why we would use a client-side framework (React, Angular, or Vue) for a pretty straightforward / static page.

totes. really, all the JS we'll need is analytics related, I think

**Comment by secretrobotron** [comment]
@cadecairos 
> what part of this ticket involves work on webmaker-app?
Nothing. My bad. Disregard :boom:

**Comment by k88hudson** [comment]
I agree adding react to the webmaker.org build process doesn't make much sense, also that Angular is not needed here since the shared nav/login etc. is not an issue.

Serving a single, separate page (and css, js) via express seems pretty sane to me, maybe you could also consider just building a static page outside the wm.org repo, deploying to s3, and proxying the webmaker.org/beta route to it?

**Comment by cadecairos** [comment]
> you could also consider just building a static page outside the wm.org repo, deploying to s3, and proxying the webmaker.org/beta route to it?

We could even just use Route 53 to direct traffic right to the static page

**Comment by cadecairos** [comment]
Seeing as how we need this to be localized, it makes the most sense to do this in webmaker.org and leverage i18n, nunjucks templating, localized routeing, etc. 

It won't use a front-end framework, but will need some JS, likely just for analytics.

**Comment by thisandagain** [comment]
Sounds good. Thanks @cadecairos

**Comment by k88hudson** [comment]
:+1:

**Comment by k88hudson** [comment]
Also, the install service (which automatically triggers an install when you hit the URL) is now live mzl.la/webmaker. It works for android/ffos and triggers a download of the android apk by default.

**Comment by secretrobotron** [comment]
Will live at  http://webmaker.org/app as per #1269.

**Comment by cadecairos** [comment]
WIP branch: https://github.com/cadecairos/webmaker.org/tree/mobile-install

**Comment by secretrobotron** [comment]
:+1: :+1: :+1:

**Comment by secretrobotron** [comment]
@cadecairos easy to throw that on heroku to see results as you work?

**Comment by cadecairos** [comment]
probably not, but I can try? lol

**Comment by cadecairos** [comment]
@secretrobotron https://wm-mobile-install.herokuapp.com/app (mobile styles only right now)

**Comment by cadecairos** [comment]
PR up for review, going to branch off the mobile branch and start #1258 (desktop install)

**Comment by thisandagain** [comment]
Awesome. Small issue with horizontal scrolling / margin ... on Android (Chrome) there is a small strip of extra space on the right. On desktop (Firefox) the user can scroll to the right about 10px.

**Comment by cadecairos** [comment]
> Awesome. Small issue with horizontal scrolling / margin ... on Android (Chrome) there is a small strip of extra space on the right. On desktop (Firefox) the user can scroll to the right about 10px.

Fixed!

**Comment by secretrobotron** [comment]
Let's try to cover GA requirements in this bug too, when they're identified in #1277.

**Comment by thisandagain** [comment]
@cadecairos Here are the GIFs for each screen. I went a little crazy with trying to optimize them (removing frames / using delays / reducing colors), but I hope this will help keep the page weight down. There are two different sizes available (2x versions shown below). Let me know if you have any questions or need anything else. This *should* be the last design asset you need AFAIK. /cc @secretrobotron @iamjessklein 

Google Drive:
https://drive.google.com/a/mozilla.com/folderview?id=0B-1AZgKn5Nc7OURSSUlKNGZFOWM&usp=sharing

![master_20150223a_editor 2x](https://cloud.githubusercontent.com/assets/747641/6343499/86f44522-bbb7-11e4-8b29-f84962c86774.gif)
![master_20150223a_share 2x](https://cloud.githubusercontent.com/assets/747641/6343500/88e18476-bbb7-11e4-8f07-be0611c694fa.gif)
![master_20150223a_templates 2x](https://cloud.githubusercontent.com/assets/747641/6343501/8a21e2d6-bbb7-11e4-8c49-3392d5c2e148.gif)

**Comment by cadecairos** [comment]
> I provided retina (2x) and normal sizes

which versions are we loading in the page?

**Comment by cadecairos** [comment]
@thisandagain should the gifs be showing Android, or FXOS?

**Comment by cadecairos** [comment]
@thisandagain 

The gifs and the cellphone svg have different aspect ratios:

![cellphonegif](https://cloud.githubusercontent.com/assets/438003/6350818/f8c4d85e-bc04-11e4-8e6d-147b932f3b78.png)

to simplify loading (# of requests) and positioning (currently requires "magic" pixel values), as well as solve the aspect ratio problem, why don't we render the cellphone svg around the animated part of the gif.

**Comment by thisandagain** [comment]
Yup! That sounds fine. Will do. :+1:

**Comment by cadecairos** [comment]
:+1: awesome!

**Comment by thisandagain** [comment]
@cadecairos Here you go! https://drive.google.com/open?id=0B-1AZgKn5Nc7OWdpQ2txUWxPRTg&authuser=0

**Comment by cadecairos** [comment]
Sweet, Thanks.

@thisandagain & @secretrobotron 
I'm concerned about how the file size of these gifs is going to negatively impact loading times on this page. In total, they will add 2.8 MB to the page load, which is going to be very noticeable on mobile connections. @toolness suggested using dithering to try and bring down the file size. I'm not sure how much of an impact that would make, but if we're okay with the drop in image quality it might be worth a shot, if the gifs must go on.

**Comment by jbuck** [comment]
Why not convert the gifs to webm/mp4? they'll compress way better that way

**Comment by thisandagain** [comment]
Agreed. I did dither and constrain the colors considerably. One idea I have is to load a static JPG in the background so that at least the user has some sort of visual while waiting for GIFs to load. Webm/MP4 isn't really an option on mobile.

**Comment by toolness** [comment]
I like the jpeg idea. Might it also be possible to drastically lower the frame-rate for devices on lower bandwidths?

**Comment by thisandagain** [comment]
Here are the JPGs. I'll take a look at how low I can get the framerate.

![master_20150224a_editor 2x](https://cloud.githubusercontent.com/assets/747641/6353934/443e6934-bc1a-11e4-82e4-e7eac6f74918.jpg)
![master_20150224a_share 2x](https://cloud.githubusercontent.com/assets/747641/6353933/443e4986-bc1a-11e4-984f-175d9f0482eb.jpg)
![master_20150224a_templates 2x](https://cloud.githubusercontent.com/assets/747641/6353935/443eca78-bc1a-11e4-9bea-993da16903cd.jpg)

**Comment by thisandagain** [comment]
Here is a package of new GIFs at 15fps. I think that is as good & small as we are going to get. :smile: 
https://drive.google.com/open?id=0B-1AZgKn5Nc7b3FDR01rVE5yLVE&authuser=0

**Comment by thisandagain** [comment]
@secretrobotron 

![top](https://cloud.githubusercontent.com/assets/747641/6355585/096d0d14-bc25-11e4-8047-35e140628944.png)
![bottom](https://cloud.githubusercontent.com/assets/747641/6355586/09703cf0-bc25-11e4-8acb-9860497f08dd.png)

**Comment by cadecairos** [comment]
work continues on this I believe

**Comment by secretrobotron** [comment]
Need to fix the responsive stuff: e.g. https://github.com/mozilla/webmaker.org/pull/1312#issuecomment-75850300
