### ISSUE TITLE
Implement desktop install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1258]
Blocks #1261
Blocks #1262
Blocks #1273
Blocks #1278

**Comment by secretrobotron** [comment]
Will live at  http://webmaker.org/app as per #1269.

**Comment by secretrobotron** [comment]
Let's try to cover GA requirements in this bug too, when they're identified in #1277.

**Comment by cadecairos** [comment]
I just realized i need to add analytics events to the send sms parts it this page
