### ISSUE TITLE
Find out if we can send text messages to phones from desktop install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1259]
- Is there a MoFo-run Twilio account we can use?

Blocks #1258
Blocks #1267

**Comment by jbuck** [comment]
I hear @simonwex has the powa to get us a Twilio account we can use

**Comment by cadecairos** [comment]
I have access to our Twillio account, and will start implementing this on Monday.

**Comment by cadecairos** [comment]
hmm I guess we can close this
