### ISSUE TITLE
QA desktop + mobile experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1261]
Blocks #1266

**Comment by secretrobotron** [comment]
Visit https://webmaker.mofostaging.net/app and follow the instructions below. File bugs in the "MWC Install Page" milestone, and reference this bug (e.g. "from #1260").

##### On a mobile device
- Scroll through the page
  - Did the text on the page load and display properly? (e.g. no apparent `{{ }}` i81n problems)
  - Did the phone outline and animated gifs load and display properly?
  - Does the layout match the [design](https://dl.dropboxusercontent.com/content_link/ORtdLH4cV5go1OJj8HqnhtAhMmuGXKIoALnmwjpaVKQLJoHpe7RbQqkF2uHA4NwN)?
- Click the "Download Webmaker" buttons (one at the top, one at the bottom)
  - **For FirefoxOS and Android**
    - were you led to the correct download page (corresponding to your OS)?
      - (were you able to install Webmaker app?)
  - **For iOS**
    - were you led to an error page explaining the limitations of the system?

- Please try this process on as many OS/browsers as you can. Ideally:
  - iOS
  - FirefoxOS 2.1+
  - Android 4.4.2+ (Chrome Mobile, Firefox Android, native browser)
  - Same list, but on a tablet

##### On desktop
- Scroll through the page
  - Did the text on the page load and display properly? (e.g. no apparent `{{ }}` i81n problems)
  - Did the phone outline and animated gifs load and display properly?
  - Does the layout match the [design](https://cloud.githubusercontent.com/assets/535012/6289869/2b9c526e-b8f1-11e4-849c-f1ec48cd7615.png)
    - *Note: a sufficiently small window will match the mobile design more closely (see above)*

- Click on the "Get App" button
  - Did a textbox appear into which you can type a phone number?
  - Is there a dropdown which lets you manipulate the country code?
  - If you type a phone number, is it formatted correctly? (e.g. `(416)-377-2810`)
  - Does changing the country code change the formatting of the phone number?

- Click the "Send Text" button
  - Is there an on-screen message telling you that you sent a text message?
  - Did you actually receive a text message?
  - Is there a link in the text message?
  - Does the link lead to an appropriate download page? (see mobile instructions above)

- Please try this process on as many OS/browsers as you can. Ideally:
  - Safari
  - Chrome
  - Firefox
  - Internet Explorer
  - Opera

##### General questions
- Was page-load time acceptable?
- Was anything confusing, wrong, or offensive?
- Were there any egregious spelling or ~~grammer~~ grammar mistakes?
- Do buttons and links act appropriately? (down states, hover states, cursor changes, etc.)

**Comment by k88hudson** [comment]
Can we add a note to please include OS + version/device in all bugs filed?

**Comment by secretrobotron** [comment]
:+1:

**Comment by thisandagain** [comment]
Functionally :ok_hand: on Firefox OS 2.2. Lots of small style issues that I will file shortly.

OS: Firefox OS 2.2
Platform: 37.0a2
Build: 20150215162503

**Comment by gvn** [comment]
Also please include STR in bugs. :metal: 

You can even use this [handy template](https://raw.githubusercontent.com/mozilla/webmaker-app/master/ISSUE_BOILERPLATE.md)!

**Comment by cadecairos** [comment]
Page + install worked on:
 FX Mobile (Aurora) on Android 5.0.1 (portrait/landscape), install page offered APK
Chrome 32 on Android 4.4.4 (portrait/landscape), install page offered APK
FX OS 2.1 on a Flame (portrait/landscape), install page offered FXos app

Desktop page tested on:
FX 37 - link sent to phone (Android), install page loaded, offered APK
Chrome 40 -link sent to phone (Android), install page loaded, offered APK

**Comment by Pomax** [comment]
fairly neat bug where you are forever stuck in the "start from scratch" template unless you force-stop the app on android - https://github.com/mozilla/webmaker.org/issues/1300

**Comment by Pomax** [comment]
It feels like we're missing a way to open up the app you just made in webmaker-app, during the share action.

**Comment by davidascher** [comment]
Agree w/ that last bit.  Seeing the app-you-just-made is a natural question.

**Comment by thisandagain** [comment]
:+1: on `It feels like we're missing a way to open up the app you just made in webmaker-app, during the share action, without having to hit back a lot of times before you get back to a menu that lets you pick "my apps"`. Mind opening a design bug to that effect @Pomax ?

**Comment by Pomax** [comment]
Can do. Also, I couldn't figure out that the app I was working on in edit view was actually "the app" instead of a design view. It feels like we need to put back the "Edit my app" vs. "Open my app" buttons, and make those different things, one an editable app, the other a usable app. Being able to accidentally press the Call or SMS button during editing and have it *do* something is extremely scary.
