### ISSUE TITLE
QA copy

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1262]
Blocks #1266

**Comment by KevZawacki** [comment]
Two minor issues with the copy: 

1) We need an “or” before “…a lesson plan” in the second box. 

2) We need a period after “colleagues” in the third box.

**Comment by edrushka** [comment]
Several changes I noted in #1263 are not reflected on staging:
1 - Button text should say Get the App
2 - In the orange box, don't capitalize the first list item after the colon (so make the "a" lowercase)
