### ISSUE TITLE
Finalize copy

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1263]
Blocks #1262
Blocks #1257
Blocks #1258
Blocks #1265
Blocks #1273

**Comment by secretrobotron** [comment]
##### Become a Maker
Webmaker takes the best part of the web — creating — and strips away the complexity. 

##### Build the Perfect App
Create exactly what you need: A website for your business, a chat app for your friends, a lesson plan for your students. 

##### Share It with the World
Webmaker creations are meant to be seen, heard and used. Share your project with friends and colleagues

**Comment by secretrobotron** [comment]
@iamjessklein is this all you need?

**Comment by iamjessklein** [comment]
Is this the final copy? I thought that we were shying away from using the word "maker" as per @LauraReynal research, no?

We also will need the copy for the desktop install page #1265

**Comment by secretrobotron** [comment]
Added #1265 to the blocking list.

@HPaulJohnson @edrushka thoughts on https://github.com/mozilla/webmaker.org/issues/1263#issuecomment-74970396 ?

**Comment by edrushka** [comment]
Laura's research indicates that the term "maker" is uncool for a specific audience (Kenya) but as far as I know it still works for other markets. One way to address this is to use a more appropriate term on the localized Kenyan (English and Swahili) versions of the site.

**Comment by edrushka** [comment]
Is there a redpen for the desktop install page?I can't see what copy is needed in  #1625

**Comment by iamjessklein** [comment]
Yep @edrushka [you can see it and drop in comments here.](https://redpen.io/sndf2a4826eed87ed6)

**Comment by secretrobotron** [comment]
@edrushka : @iamjessklein posted new mocks in https://github.com/mozilla/webmaker.org/issues/1265#issuecomment-75151724 with copy and design refinements. Can you r?

**Comment by secretrobotron** [comment]
From #1265:
![desktop 2x-revision](https://cloud.githubusercontent.com/assets/535012/6289869/2b9c526e-b8f1-11e4-849c-f1ec48cd7615.png)

All finals are on [dropbox](https://www.dropbox.com/sh/if9ui2246h91qxv/AAB5Ri0b82HZ3mBhMDcKFwdFa?dl=0)

**Comment by edrushka** [comment]
1 - In the blue "Become a Maker" box, make sure those are em-dashes
2 - I would prefer the button text to say Get the App 
3 - In the orange box, don't capitalize the first list item after the colon (so make the "a" lowercase)
4 - Is there a reason there isn't an "or" before "a lesson plan for your students"?
5 - Shouldn't the text on the Twilion page button read "Text me" or "Send me a text"? When you click that button, you're not actually texting someone.
6 - The Twilio small print says "Your call is connected..." Are you calling someone? 
7 - Overall I think there should be more explanation on the Twilio page. I don't understand what's going to happen when I enter my number into that box.
8 - Can we remove the American flag from the box? It makes me think this is for US only (Is it?)
9 -  If it's international, be aware that we're using the North American convention for phone numbers in the hint text.

**Comment by KevZawacki** [comment]
@edrushka, regarding #4: We could go either way. If you think it reads better with an "or," let's do it.

**Comment by edrushka** [comment]
Sure, let's do it. So decision = "...friends, or a lesson plan for your students."

**Comment by LauraReynal** [comment]
Hey guys, I know im coming late - I was flying - and maybe this is finished -  but to answer @edrushka and @iamjessklein question about being a Maker =
It is a common feeling from Kenya, Bangladesh and India. "Become a maker" does not speak to this audience, so we should make sure there is another language for these audience. 
Do we have localized language for these countries yet ?

**Comment by secretrobotron** [comment]
Thanks @LauraReynal .

Spoke with @HPaulJohnson @edrushka and @KevZawacki about it a bit.
- "Maker" should be fine for MWC audience, because there's lots of context about the app otherwise
- We plan to send out a localization message ASAP (see https://github.com/mozilla/webmaker.org/issues/1273)
  - This bug needs to close first so @cadecairos can land the changes
  - In the message to transifex contributors, we can say "don't feel the need to use 'maker'"
- @KevZawacki is going to write a couple of versions we can use anyway

@LauraReynal do you have some suggestions for what to use instead?

**Comment by secretrobotron** [comment]
:melon: :banana: :strawberry:

**Comment by KevZawacki** [comment]
Yep, on it! I'll write up copy that's slang- and quirk-free. @LauraReynal, all suggestions welcome.

**Comment by secretrobotron** [comment]
@thisandagain and I spoke about this copy this morning, and agreed that, for MWC, what @HPaulJohnson, @edrushka and @KevZawacki provided (above) is fine.

We'll follow up and provide much better localization for a bigger audience after MWC.
