### ISSUE TITLE
Design desktop install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1265]
##### Hand-off list
  - [x] flat png
  - [x] svg
  - [x] fonts (if required)

Blocks #1264
Blocks #1258

**Comment by iamjessklein** [comment]
I uploaded the mockup. [Please drop your feedback into Redpen.](https://redpen.io/sndf2a4826eed87ed6)

@HPaulJohnson - please see notes on the copy 
@simonwex - please see notes on Twilio privacy policy 
@thisandagain - thanks for your quick response

![desktopv3 2x](https://cloud.githubusercontent.com/assets/535012/6259771/4cb994e6-b7a4-11e4-9dd2-d712b4c840e8.png)

**Comment by iamjessklein** [comment]
[Revised mockups with specs here can be found here.](https://www.dropbox.com/sh/if9ui2246h91qxv/AAB5Ri0b82HZ3mBhMDcKFwdFa?dl=0)  

[Revised interaction flow for user input - drop comments in Redpen.](https://redpen.io/vj0e56e430443dae7d)
![artboard 1](https://cloud.githubusercontent.com/assets/535012/6277361/f3f53a6e-b85b-11e4-9b74-444c2e0f1d5b.png)

**Comment by secretrobotron** [comment]
@thisandagain can you take a look at these and r?

**Comment by KevZawacki** [comment]
Beautiful mockups! Thanks, @iamjessklein 
Quick capitalization: Can we do "It" in "Share it with the World."

cc @HPaulJohnson

**Comment by thisandagain** [comment]
@iamjessklein looks great Jess. One minor issue with the centering on the "Get App" button, but otherwise R+ :cake:

**Comment by iamjessklein** [comment]
awesome, will change and upload revisions.

**Comment by iamjessklein** [comment]
Revised: 
![desktop 2x-revision](https://cloud.githubusercontent.com/assets/535012/6289869/2b9c526e-b8f1-11e4-849c-f1ec48cd7615.png)

All finals are on [dropbox](https://www.dropbox.com/sh/if9ui2246h91qxv/AAB5Ri0b82HZ3mBhMDcKFwdFa?dl=0)
