### ISSUE TITLE
Push mobile and desktop install pages to prod

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1266]
Blocks https://github.com/mozilla/webmaker-app/issues/1246

- [ ] jenkins it up
- [x] change bitly links
- [x] make sure those links work

**Comment by cadecairos** [comment]
technically, this is done. reopen if you disagree

**Comment by secretrobotron** [comment]
Just leaving this here until @mmmavis moves her code up too. Latest revisions aren't on prod.

**Comment by secretrobotron** [comment]
Yay! Done!
