### ISSUE TITLE
Implement "send text to mobile" feature on desktop install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1267]
- Is there a rate limiter or spam feature provided by the Twilio API (if that's what we use)?

Blocks #1258

**Comment by secretrobotron** [comment]
@cadecairos : did you look into any preventative measures here?
Otherwise, I think this is wrapped up by #1282, right?

**Comment by cadecairos** [comment]
@secretrobotron preventative measures?

**Comment by secretrobotron** [comment]
@cadecairos spam, rate-limiting, etc.

**Comment by cadecairos** [comment]
@jbuck insists we take the time later this week to rate limit

I think it's a good idea, but shouldn't block us, as long as we can monitor using loggins

**Comment by cadecairos** [comment]
@secretrobotron can we close this?

**Comment by secretrobotron** [comment]
@cadecairos Yep! Can you just outline a plan to monitor for spam?

**Comment by cadecairos** [comment]
At the least we can use Kibana: 
https://loggins.mofoprod.net/#/dashboard/elasticsearch/STAGING%20SEND%20DOWNLOAD%20LINK
The IP Address table there lists the top 15 IP's hitting the `/app/send-download-link`

@secretrobotron what do you think?

**Comment by secretrobotron** [comment]
Guess it makes no sense to hash them there if we're looking to prevent spam?

(I can't see what's behind that link, btw.)

**Comment by cadecairos** [comment]
hash IP addresses?

**Comment by jbuck** [comment]
Had a quick chat with Adam, so long as we nuke logs >6 months old we're good for data retention.

Still need to add rate-limiting though.

**Comment by secretrobotron** [comment]
@cadecairos @jbuck mind updating on where we got with this today?

**Comment by cadecairos** [comment]
A rate limit enabling patch for the sawmill sms worker is in review. 

https://github.com/mozilla/sawmill/pull/38
