### ISSUE TITLE
Decide on a route for webmaker install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1269]
Current thinking is http://webmaker.org/beta to host the install page for webmaker app.

Blocks #1268
Blocks #1266
Blocks #1257
Blocks #1258

**Comment by HPaulJohnson** [comment]
what about http://webmaker.org/app?

Thinking is that when we move out of beta we could still use the same page and any "juice" that we've developed via MWC, press and other promotion during the Beta phase?

**Comment by secretrobotron** [comment]
That's what I was thinking too. Couple of potential concerns:
- confusion with Appmaker (not sure if audiences overlap though, or if we care)
- do we want to signal Webmaker app is production-ready? /app says that to me, a bit.

**Comment by secretrobotron** [comment]
@thisandagain @davidascher thoughts?

**Comment by thisandagain** [comment]
:+1: on `webmaker.org/app`

**Comment by davidascher** [comment]
Yes I dont worry about appmaker.

**Comment by secretrobotron** [comment]
Hooray! Decided!
Let's go with http://webmaker.org/app .

**Comment by cadecairos** [comment]
/me edit's all the `/beta`s in the WIP branch
