### ISSUE TITLE
Design mobile install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1270]
From https://redpen.io/p/od396a13bd17f4227e via @iamjessklein 

##### Hand-off list
  - [x] flat png
  - [x] svg
  - [x] fonts (if required)

Blocks #1257

**Comment by iamjessklein** [comment]
[Here are all the files for this project.](https://www.dropbox.com/sh/if9ui2246h91qxv/AAB5Ri0b82HZ3mBhMDcKFwdFa?dl=0) 

If you need something that isn't there - just let me know.

cc/ @jbuck @cadecairos
