### ISSUE TITLE
Add language dropdown picker to MOI splash page

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker.org#1271]
Due to the great progress in #1205, we should add a dropdown language picker to the page.

Since high-quality translation is necessary on this page, let's only use languages that are at least 90% complete (so, currently, Polish (Poland) 100%, Spanish 100%, Finnish 100%, Dutch 100%, Danish  (Denmark) 100%, Portuguese (Brazil) 97%, Albanian 97% Hindi (India) 97%)

Normally the languages are arranged in alphabetical order. Do we want to highlight our P1 languages (Bangla, Hindi, Brazilian Portuguese) at the top (if that's even possible) @benrito @HPaulJohnson

**Comment by benrito** [comment]
rad!

**Comment by mmmavis** [comment]
@sabrinang any suggestion on where the dropdown should be located?

**Comment by HPaulJohnson** [comment]
+1 to highlighting our P1 languages at the top of the dropdown list, if possible.

**Comment by sabrinang** [comment]
For the dropdown menu - use the existing webmaker dropdown functionality on https://webmaker.org and for styling remove the box (as seen on the new teach.webmaker.org designs - i.e. https://redpen.io/nh043da2fe4430ac92) 

On mobile, it will show the collapsible icon and when clicked will revel language dropdown (tabzilla is hidden on mobile).

**Comment by mmmavis** [comment]
@sabrinang 
> On mobile, it will show the collapsible icon and when clicked will revel language dropdown (tabzilla is hidden on mobile).

For mobile, did you mean <768px ?

**Comment by mmmavis** [comment]
Hey @alicoding :D
Thanks for committing the patch for the existing localization library. I've pushed the code to my MOI staging server on Heroku: https://moi-splash.herokuapp.com/localweb
Q1) Do I have to include `npm run download-locales` in `postinstall` in package.json to make the locale files loaded?  Right now the language picker only has en-us.
Q2) Do we have control over what locale gets shown in the dropdown?   (eg., highlight a few P1 languages so they appear first)

**Comment by alicoding** [comment]
@mmmavis for your testing purposes you can include that in the `postinstall`, yes.

**Comment by mmmavis** [comment]
Up on https://moi-splash.herokuapp.com/localweb.  :dancer: 
@alicoding, when you get a chance can you review my commits? I can squashed all the localization commits into one if that's easier for you to review.  Open PR here: https://github.com/mozilla/webmaker.org/pull/1246

**Comment by mmmavis** [comment]
I believe this is done.  Gonna close this ticket now.

CC @alicoding
