### ISSUE TITLE
Setup localization for install page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1273]
##### Tasks
- [x] upload and setup auto-sync for new locale string json file
- [x] notify transifex communities (mirroring list in https://github.com/mozilla/webmaker-app/issues/763)

##### Locales
* Bengali [P1]
* Hindi [P1]
* French [P1]
* English [P1]
* Panjabi
* Kannada
* Oriya
* Telugu
* Tamil
* Malayalam
* Portuguese (Brazil) 
* Swahili (Kenya)

**Comment by secretrobotron** [comment]
cc @cadecairos

**Comment by secretrobotron** [comment]
@alicoding do you mind double-checking that I have https://www.transifex.com/projects/p/webmaker/resource/webmakerorgs-appjson/ set up properly?

**Comment by alicoding** [comment]
Small fix, but all good now.
