### ISSUE TITLE
claiming a badge has a pretty busted success message

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/webmaker.org#1274]
When you claim a badge, this is what I see:

"Check your email () for more information about the badge you've just earned."

Mostly this "email ()" needs to be fixed.

**Comment by k88hudson** [comment]
this is probably due to login using a different email key now

**Comment by ScottDowne** [comment]
Fixed: https://github.com/mozilla/webmaker.org/commit/bc393dd149dca003c2d82f4007dda681e36c8b58
