### ISSUE TITLE
Install Page needs metrics (desktop & mobile are the same)

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker.org#1277]
:bar_chart:  :chart_with_upwards_trend: :chart_with_downwards_trend: :bar_chart:  :chart_with_upwards_trend: :chart_with_downwards_trend: :bar_chart:  :chart_with_upwards_trend: :chart_with_downwards_trend:

Let's test out this new metrics checklist:

### Metrics Requirements Checklist for Desktop install, and iOS friendly error page

- [x] We **need** to be able to count/measure:
  * Basic GA pageviews
    * on install page
    * on iOS error page
  * Send install SMS (button push)
  * Download button push

- [x] We **would like** to be able to count/measure:
 * How many people actually look at the page under the fold?
 * Which region is chosen most often for sending SMSs?

- [x] We have investigated (or asked Adam) which of these items are already being measured, and which need new 'instrumentation'
 * @cadecairos  has GA on the install page already
 * @k88hudson is GA setup on the iOS error page (or on the install service in general)?
 * Just need to add events to the page, which can happen in https://github.com/mozilla/webmaker.org/issues/1258
 * @adamlofting did I miss anything here?

- [x] Where new 'instrumentation' is required ticket(s) have been filed for the build phase
  * @cadecairos will implement in https://github.com/mozilla/webmaker.org/issues/1258
    * or this issue, it he wants

- [x] We have decided on the level of reporting needed, on a scale of: '_Ask Adam two weeks later how it went_' to '_We need a realtime dashboard and my phone to ring if this number changes by more than half a percentage point_'
  * Needs to be alive before MWC, and throughout
  * Realtime updates not needed
  * Would be nice to have a summary after MWC so we can revise the experience based on data
  * @thisandagain ^^ look right?

- [x] Decide what 'success looks like' by setting goals for the numbers you want to track
  * Success == some % of visitors click the download/sms button
  * Matching Webmaker conversion would be good (~7%)
    * But, would hope that we have higher conversion based on content and audience (MWC)
    * @thisandagain any more solid goal to cite here?

- [x] If you are planning to run A/B tests or similar, please briefly outline the testing strategy. 
 * *No A/B tests yet, but might run afterward based on data we collect.

**Comment by adamlofting** [comment]
@secretrobotron can you answer and check-off this list please? Then we'll file implementation tickets.

**Comment by thisandagain** [comment]
cc @k88hudson I have a feeling we'll want some instrumentation within the install service as well.

**Comment by k88hudson** [comment]
agreed :+1:

**Comment by secretrobotron** [comment]
@adamlofting how'd I do?

**Comment by cade** [comment]
I am the king of GA. :crown:

**Comment by cadecairos** [comment]
Lol!

**Comment by davidascher** [comment]
On the region thing -- are we asking about the GeoIP of the visitors, or the country/area code of the SMS?

**Comment by secretrobotron** [comment]
Haha @cade apologies. Blame @cadecairos for the IRC nick he chose.

**Comment by secretrobotron** [comment]
@davidascher I just assumed the country code.

**Comment by adamlofting** [comment]
@secretrobotron: what are we storing with regards to the phone numbers for SMS? (and where are we storing this?)

**Comment by adamlofting** [comment]
@secretrobotron you did great! This checklist process needs some refinement from me though.

Remaining action items for my tracking:
- [ ] Basic GA on iOS (and any other error page)
- [ ] GA on install service (if separate to error page)
- [ ] Basic dashboard

Nice to have:
- [ ] Who reads below the fold? (ie scrolls?)

**Comment by cadecairos** [comment]
> Who reads below the fold? (ie scrolls?)

@adamlofting Tips on implementing this? i.e. watch `window.scrollY` and trigger after a certain amount? fire on first scroll event, etc.

**Comment by secretrobotron** [comment]
@cadecairos my guess: measure the height of the first section after page load, and see if `window.scrollY` falls beyond it.

**Comment by secretrobotron** [comment]
@adamlofting 

> what are we storing with regards to the phone numbers for SMS?

Not sure I follow. I don't think we're storing **anything**. Should/can we?

**Comment by cadecairos** [comment]
> Not sure I follow. I don't think we're storing anything. Should/can we?

sawmill will log phone numbers, but they aren't stored afaik. Twilio stores phone numbers for 30 days iirc

**Comment by secretrobotron** [comment]
@cadecairos can you just remove the phone number form sawmill logs to circumvent any data practice problems?

We need to add a blurb at the bottom of the page that says something to the effect of...

> Text messages are sent to your phone via a company called Twilio. This information will be stored for no more than 30 days, and will not be used for any other purposes. For more information, see [Twilio's privacy policy](https://www.twilio.com/legal/privacy).

**Comment by secretrobotron** [comment]
@jbuck @jp : @adamlofting says you have a system to log hashed phone numbers to prevent malice in the call congress setup. Can we reuse that here?

**Comment by cadecairos** [comment]
At this point, the libs handling the SQS messages likely won't let us censor the numbers. we can turn off all logs

**Comment by adamlofting** [comment]
The install _service_ UA detection and warning messages are going to be moved into this install _page_. 

We no longer need to instrument the install service, but will track further events on the install page once this code is moved across.

**Comment by secretrobotron** [comment]
@k88hudson can you point @adamlofting at the code you moved (or are moving) over?

**Comment by secretrobotron** [comment]
My guess: https://github.com/mozilla/webmaker.org/pull/1320

**Comment by secretrobotron** [comment]
@cadecairos can you link the change you made to sawmill here?

**Comment by adamlofting** [comment]
No further instrumentation needed here now that the install page prevents the 'wrong' user agents from trying to click the download button.

**Comment by adamlofting** [comment]
For simple reporting I've setup a GA custom report.

This link shares the custom report template, but you have to use this template to create the report in your account:
https://www.google.com/analytics/web/template?uid=Q8BI8Kc2TYm2RwKuzgBf2w

**Comment by thisandagain** [comment]
Great. Thanks @adamlofting! I added this to a shared dashboard called "App Installation" as well.
