### ISSUE TITLE
Links to the tools not working in my language

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker.org#1279]
Links to Goggles, Thimble and Popcorn on webmaker.org is not working in my locale.
https://goggles.webmaker.org/da-DK
https://thimble.webmaker.org/da-DK
https://popcorn.webmaker.org/da-DK/editor/

Also could we have the links on https://webmaker.mofostaging.net/da-DK/tools for the tools changed so they link to mofostaging.net instead of webmaker.org when you are on the staging server.

**Comment by alicoding** [comment]
@jdotpz can we also update .env to add `da-DK` to the rest of our apps? :)

**Comment by scootergrisen** [comment]
Could this issue be given higher priority ?

Because i would like other people to test the translating on the website. But right now they cant test any of the tools in webmaker.org in my language.

**Comment by jdotpz** [comment]
@scootergrisen This was actually done 14 days ago!  @alicoding shall we close the issue?

**Comment by alicoding** [comment]
@jdotpz it seems like we only have enabled this for webmaker.org but not the rest of the apps. If you try click on those links above none of them works @jdotpz.

**Comment by jdotpz** [comment]
Ah, gotcha.  I thought that enabled it for all of the apps.  Are we clear to do this today then?

**Comment by alicoding** [comment]
Lets do it for all today if possible :)

**Comment by jdotpz** [comment]
Can you please tell me the specific apps this is going into?  ala, thimble, goggles, butter, ... makeapi?  webmaker-profile2?  wmlogin?

**Comment by alicoding** [comment]
thimble
makeapi
makevalet
webmaker-profile-2
webmaker-login
goggles
popcorn

I think that's all if I didn't miss any.

**Comment by jdotpz** [comment]
This is now completed!
FYI, makeapi and webmaker-profile-2 do not have languages set.

**Comment by alicoding** [comment]
Thanks @jdotpz !
