### ISSUE TITLE
Need "Webmaker mobile partnership" PDF link to plug in to MOI splash page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/webmaker.org#1283]
@edrushka 

This is a reminder so we won't forget to fix a broken link on the splash page.

**Comment by edrushka** [comment]
I've asked Ben and/or Bobby to clarify what they want here. I'll update this when I hear back

**Comment by edrushka** [comment]
@jbuck is creating http://stuff.webmaker.org/mobile_webmaker_partners.pdf  @mmmavis, please link to that and @benrito will add the file when it's ready.

**Comment by mmmavis** [comment]
I added this to the build and it's now live on staging: https://moi-splash.herokuapp.com/localweb.  I guess we can close this ticket?
