### ISSUE TITLE
Choose a "From" phone number based on the country code of the "to" number

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker.org#1288]
It will probably save users monies if they get messages from local numbers, when we can make it happen.

i.e. Spanish Number for Spain (MWC in Barcelona!) 

cc/ @thisandagain @simonwex

**Comment by cadecairos** [comment]
Looks like twilio doesn't have any Bangladeshi or Indian numbers available

**Comment by secretrobotron** [comment]
@cadecairos can you grab a Spanish number?

**Comment by simonwex** [comment]
Due to local regulation, we must have a business or personal address in Spain for a +34 number. Do we have one we can use?

**Comment by secretrobotron** [comment]
Not that I'm aware of.

@thisandagain @davidascher anyone in Spain we can ask?

Otherwise, we can send from the US number for the time being. We're going to have to do that for people who don't have Spanish SIMs anyway, right?

**Comment by thisandagain** [comment]
@vazquez any thoughts?

**Comment by davidascher** [comment]
Maybe @toniher can help?

**Comment by toniher** [comment]
Hi, I could try to buy a Movistar prepaid card tomorrow, and I could give it to you phisically before MWC starts.

**Comment by secretrobotron** [comment]
@Saallen has a friend who might be able to help too.

@simonwex : we just need a name/address, and we can do the purchase through Twilio?

**Comment by cadecairos** [comment]
I had a chat with @vazquez , and he doesn't have any family still living in Spain. He may know some folks over there though.

**Comment by thisandagain** [comment]
@simonwex Given that you have experience with this can you make a call here?

**Comment by davidascher** [comment]
@toniher can we use your name and address? We just need a local to behind the number

**Comment by simonwex** [comment]
@toniher as @davidascher said, we don't need a SIM, we only need an address to assign to the number we purchase through Twillio. If you're comfortable doing this, could you email me your address? simon@mozillafoundation.org

**Comment by simonwex** [comment]
Number purchased with @toniher's help. @cadecairos emailed you the digits.

**Comment by secretrobotron** [comment]
@cadecairos have you got some stats on # of calls so far? Let's keep an eye on traffic over the next few days.

**Comment by cadecairos** [comment]
looks like 87 sms api hits today, 80 successfully delivered

**Comment by secretrobotron** [comment]
Were we able to the buy the right number today?
Twilio stats still look sane?

**Comment by cadecairos** [comment]
We have a number now, patch is in review: mozilla/lumberyard#29

charges on Twilio at ~$9.50

**Comment by secretrobotron** [comment]
Closing this to continue for longer-term in #1393.
