### ISSUE TITLE
Add a button to clear profile

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1289]
The developer menu should have a "clear profile" button so devs don't have to uninstall/reinstall app when they want to check things.

**Comment by secretrobotron** [comment]
cc @alicoding

**Comment by alicoding** [comment]
@secretrobotron wrong repo :P

**Comment by secretrobotron** [comment]
Hahah sigh. Thanks @alicoding .

**Comment by secretrobotron** [comment]
https://github.com/mozilla/webmaker-app/issues/1317
