### ISSUE TITLE
Downloading copy needs tweak

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1290]
On FF on Android 5, I get a screen that says: "Downloading apk (requires Android 4.2+)".

* apk is jargon.  Just say "downloading the app"
* the page should know what android version I have (likely way more accurately than I do as a user), so it seems needlessly confusing

**Comment by k88hudson** [comment]
Good suggestions. Unfortunately there is no way to know what version you have in Firefox for Android, so I feel like we should keep the version notice for now.

**Comment by k88hudson** [comment]
Moving to webmaker-app
