### ISSUE TITLE
Phones are empty

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker.org#1294]
*OS:* OSX
*Browser:* Chrome 40.0.2214.111 (64-bit)
*Screenshot:* https://www.dropbox.com/s/9dgjaotu8cb4a99/Screenshot%202015-02-24%2010.09.12.png?dl=0

**Repro Steps:**
1. Load page https://webmaker.mofostaging.net/app

**Expected:** See contents in phone wrapper per design
**Actual:** See screenshot

**Comment by gesa** [comment]
Reproduced on Firefox 35 & 37

**Comment by gvn** [comment]
Related to: #1261
