### ISSUE TITLE
Install Page - Multi-line headlines need line-height increased

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker.org#1295]
The headlines are feeling too tight here:
![screen shot 2015-02-24 at 12 52 59 pm](https://cloud.githubusercontent.com/assets/747641/6355795/bd40543a-bc26-11e4-9b8e-02ef6295a1b5.png)

**Comment by gvn** [comment]
See also:
https://www.dropbox.com/s/lcpxghmugogmcic/Screenshot%202015-02-24%2010.27.36.png?dl=0

**Comment by errietta** [comment]
I get the same as @gvn on tablet on landscape mode
