### ISSUE TITLE
Mozilla tab is missing

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker.org#1297]
*OS:* OSX
*Browser:* Chrome 40.0.2214.111 (64-bit)
*Screenshot:* https://www.dropbox.com/s/br2jvgwxft3vu6a/Screenshot%202015-02-24%2010.13.24.png?dl=0

**Repro Steps:**
1. Open page https://webmaker.mofostaging.net/app

**Expected:** See Mozilla tab in upper right corner
**Actual:** No Mozilla tab visible

**Comment by thisandagain** [comment]
Good catch. I'm cool not including Tabzilla for this sprint however – particularly considering the weight.

**Comment by gvn** [comment]
Yeah, I'm not a fan of Tabzilla. :+1:
