### ISSUE TITLE
US Phone number is problematic

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker.org#1299]
*OS:* OSX
*Browser:* Chrome 40.0.2214.111 (64-bit)
*Screenshot:* https://www.dropbox.com/s/ilpig5dkx04aelb/Screenshot%202015-02-24%2010.17.47.png?dl=0

**Repro Steps:**
1. Choose US
2. Enter 2061231234

**Expected:** "Send Text" button should be enabled
**Actual:** "Send Text" button is disabled

**Comment by gvn** [comment]
Related to: #1260

**Comment by cadecairos** [comment]
I don't think 123 is a valid exchange for a US number, so in this case, the behaviour is expected.

perhaps we want better error reporting?

**Comment by gvn** [comment]
Yeah, if there's some validation happening it should be more obvious to the end user via the UI.
