### ISSUE TITLE
[Android] Start app, pick "start from scratch", then try to get back to the main menu.

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker.org#1300]
You can't. The tucan refuses to back down.

**Comment by k88hudson** [comment]
This is a dupe of mozilla/webmaker-app/#1304

Also, please file QA bugs related to webmaker-app in that repo if possible :+1:

**Comment by Pomax** [comment]
I could have sworn that's where I was. weird wrong-repo filing.
