### ISSUE TITLE
Install page: download button results in infinite loop

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker.org#1301]
QA-ing for #1261

*OS:* Mac OS X
*Browser:* Chrome 40 and Firefox (35 & 37)

**Repro Steps:**
1. Click "download webmaker"

**Expected:** Not entirely certain
**Actual:** Browser loads a blue page with "undefined" in the middle, then reloads a page identical to the original download page, but hosted on heroku

**Comment by cadecairos** [comment]
This is a dupe of #1305
