### ISSUE TITLE
Got a flash of "undefined" on https://wm-mobile-install.herokuapp.com/app

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker.org#1305]
Using Firefox on Mac OSX, I went to `https://webmaker.mofostaging.net/app`, scrolled to the bottom, and got redirected to `https://wm-mobile-install.herokuapp.com/app`

then

* saw a flash of "undefined" before the page rendered
* saw the same page I was just at, AFAICT.

**Comment by davidascher** [comment]
to be clear: i can't actually download the app using SMS or otherwise from this page.

**Comment by cadecairos** [comment]
I think this is an install service bug

@k88hudson what's going on here?

**Comment by cadecairos** [comment]
this might get solved by #1315

**Comment by secretrobotron** [comment]
@k88hudson ping!

**Comment by k88hudson** [comment]
This is resolved!
