### ISSUE TITLE
Install Page - Media query for "desktop" width is too wide

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker.org#1306]
We should define "mobile" more conservatively. Right now it looks like the user's browser window needs to be greater than ~ 800px 

![screen shot 2015-02-24 at 1 29 25 pm](https://cloud.githubusercontent.com/assets/747641/6356913/b7894030-bc2e-11e4-8ba6-ad8f916ecc35.png)

**Comment by cadecairos** [comment]
So tablet-sized screens should see the desktop UI?

**Comment by thisandagain** [comment]
Yes

**Comment by cadecairos** [comment]
#1315 should fix this

**Comment by secretrobotron** [comment]
Fixed by #1320.
