### ISSUE TITLE
SMS doesn't work on install page

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker.org#1308]
From Chrome/Mac OS X to a phone on Virgin mobile, also to a phone on WIND;

Pressed send, got the confirmation message, but no SMS was received.

**Comment by k88hudson** [comment]
cc @jbuck @cadecairos

**Comment by cadecairos** [comment]
@k88hudson which site? heroku or mofostaging?

**Comment by k88hudson** [comment]
https://wm-mobile-install.herokuapp.com/app

**Comment by cadecairos** [comment]
Yeah, that isn't setup to work, use mofostaging

**Comment by cadecairos** [comment]
https://webmaker.mofostaging.net/app

**Comment by k88hudson** [comment]
Ok, I updated the bit.ly link. However, doesn't seem to work on staging either  :(

**Comment by cadecairos** [comment]
Sawmill-staging had crashed due to an unrelated newrelic error, it should work now

**Comment by cadecairos** [comment]
@k88hudson shall we mark this resolved?

**Comment by thisandagain** [comment]
\o/
