### ISSUE TITLE
Windows phone - not told not supported

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker.org#1314]
I used IE 10's developer tools, and set my UA as windows phone. "Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident / 6.0; IEMobile / 10.0; ARM; Touch)"
I expected to get some text explaining it's not supported. Instead, I'm forwarded back to /app

**Comment by errietta** [comment]
cc @k88hudson

**Comment by errietta** [comment]
Note - verification from someone with a real windows phone would be nice :p

**Comment by secretrobotron** [comment]
Same problem for iPads.

**Comment by secretrobotron** [comment]
@k88hudson handled by latest build?

**Comment by k88hudson** [comment]
Yep! should at least show a texting field now.
