### ISSUE TITLE
Design QA: remaining issues

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker.org#1321]
[See mobile design](https://dl.dropboxusercontent.com/content_link/reCZcKO41zF8sa3gRydqje84wlDNBwqvSmWp1FxmITVvWTCuTbBeRYOdfgM3t6ie)

* SMS fields don't look right on a small screen ![image](https://cloud.githubusercontent.com/assets/1455535/6362652/92abf7ec-bc5d-11e4-8b5d-01dc78f6b88a.png)
* descriptions not italic
* button font size/padding is off
* previews don't fit on screen
* uneven spacing between download button and top of phone preview
![image](https://cloud.githubusercontent.com/assets/1455535/6362442/29d9dec0-bc5b-11e4-81b2-7d5a54588251.png)
*  uneven spacing between bottom of phone and top of heading text ![image](https://cloud.githubusercontent.com/assets/1455535/6362457/50751126-bc5b-11e4-8fa7-737451e2ab2e.png)
* breakpoint is too high
* bottom border on navbar should be removed

[See desktop design](https://cloud.githubusercontent.com/assets/535012/6289869/2b9c526e-b8f1-11e4-849c-f1ec48cd7615.png)

* line height too tight on descriptions
* headings on second and third panels too large
* line height too tight on headings ![image](https://cloud.githubusercontent.com/assets/1455535/6362551/4d2284da-bc5c-11e4-98df-763ab25e3d85.png)
* text is not centred with image 
![image](https://cloud.githubusercontent.com/assets/1455535/6362583/9d3fe32c-bc5c-11e4-8817-8f4b9815ae0b.png)
* alignment/spacing for sms form
![image](https://cloud.githubusercontent.com/assets/1455535/6362682/f59bee16-bc5d-11e4-9822-1f4d218f7cc5.png)
* disclaimer text is too small

**Comment by iamjessklein** [comment]
* Country drop down alignment isn't consistent on SMS input:
![screen shot 2015-02-26 at 10 33 16 am](https://cloud.githubusercontent.com/assets/535012/6394968/32e83720-bda3-11e4-8c4b-32067dd833ee.png)

* Call to action button on pane before the footer is missing. See [here](https://redpen.io/pm3459a122240a34a5)

* Twilio copy should be left aligned on mobile. 
![screen shot 2015-02-26 at 10 38 47 am](https://cloud.githubusercontent.com/assets/535012/6395040/d0ec6d24-bda3-11e4-975f-c8b67365160f.png)

* Footer design not implemented (this is a nice to have: not blocking shipping)
![screen shot 2015-02-26 at 10 42 36 am](https://cloud.githubusercontent.com/assets/535012/6395113/531823d8-bda4-11e4-879a-f5debe4f4535.png)
