### ISSUE TITLE
redirect badges.webmaker.org to blog.webmaker.org/badges

### ISSUE THREAD

**Issue by hannahkane** [mozilla/webmaker.org#1326]
http://badges.webmaker.org/ currently goes to a page of old badges that you can no longer apply for. We should redirect this page to blog.webmaker.org/badges even it it's just a temporary measure until we get a proper badges welcome page set-up. We've had a few emails from confused people. 

/cc @LucyeoH

**Comment by jdotpz** [comment]
I can do this.

**Comment by jbuck** [comment]
More context: https://bugzilla.mozilla.org/show_bug.cgi?id=967755

**Comment by jdotpz** [comment]
Redirect is set.

**Comment by ScottDowne** [comment]
Confirmed!

**Comment by LucyeoH** [comment]
Hate to re-open this but can we also make http://discover.openbadges.org/ redirect to the badges page. More confused people! cc. @ScottDowne @hannahkane @jdotpz

**Comment by ScottDowne** [comment]
@LucyeoH should probably file a new ticket for this. It'll likely get more attention that way.

**Comment by jdotpz** [comment]
@LucyeoH which page specifically should we redirect to?  blog.webmaker.org/badges ?

The discover page is currently working, so I'm curious why we'd redirect it?

**Comment by simonwex** [comment]
@LucyeoH could you file the new ticket and mention this one?

**Comment by edrushka** [comment]
@hannahkane  I'm closing the Misc dev ticket. Just reminding you to move or label this as you see fit so it doesn't get lost.
