### ISSUE TITLE
QA MOI splash page for MWC 

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker.org#1338]
Please help us QA this page ( https://webmaker.org/localweb )

- Ensure the link to the Open Beta works. It should send you to: https://webmaker.org/app
- Ensure the video plays with audio & the video shows up in a lightbox popup
- Ensure you can access all the research reports
- Ensure the mailto links on the contact CTAs work
- Ensure you can use the language dropdown menu to select other languages

Thank you!
cc @secretrobotron 

-----
Fixed Friday Feb 27:
- [x] [Global Users A Locally Relevant Web: Early Research & Recommendations PDF](http://mzl.la/research) 
- [x] [Webmaker India research report PDF](http://mzl.la/india) (report won't be ready in time. link greyed out )
- [x] replace placeholder video with the real one: https://www.youtube.com/watch?v=3LkLj8yogzk

What's currently **missing**:
- [ ] [partner with us PDF](https://stuff.webmaker.org/mobile_webmaker_partners.pdf )  (currently broken link, Ben and Bobby will update over the weekend)

**Comment by HPaulJohnson** [comment]
Also missing: https://stuff.webmaker.org/mobile_webmaker_partners.pdf (currently broken link for "partner with us")

**Comment by mmmavis** [comment]
@HPaulJohnson thanks! I updated the list above (I assume the PDF will be ready tomorrow as well?)

**Comment by edrushka** [comment]
@mmmavis can we close this?

**Comment by mmmavis** [comment]
for sure
