### ISSUE TITLE
Green button shouldn't have a top border

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker.org#1342]
It would look better if it was just all the same green 

![image](https://cloud.githubusercontent.com/assets/1455535/6404522/126b68ca-bde7-11e4-82af-1b5c01733e1d.png)

**Comment by mmmavis** [comment]
Hey @k88hudson 
I'm seeing this on webmaker.org as well.  It's the half transparent box-shadow that's making the blurry top edge. (`box-shadow: 0px 0.4rem 0px #328F70, 0px 0.1rem 0px rgba(255, 255, 255, 0.5) inset`)
What should we do?

**Comment by k88hudson** [comment]
Hm perhaps we should revisit at a later time when we revise buttons styles across the project
