### ISSUE TITLE
Pick a screencap to add to the video section as background

### ISSUE THREAD

**Issue by mmmavis** [mozilla/webmaker.org#1343]
It will be a screencap from the video. [working in progress video here](http://videos.blinktower.com/medias/qahh1il5yt)

cc @edrushka

**Comment by mmmavis** [comment]
1:14 from http://videos.blinktower.com/medias/qahh1il5yt

![1:14 from http://videos.blinktower.com/medias/qahh1il5yt](https://cloud.githubusercontent.com/assets/2896608/6404919/33c105ee-bdd2-11e4-863e-e737b843dc7c.png)

**Comment by edrushka** [comment]
cc @HPaulJohnson

**Comment by mmmavis** [comment]
0:10 from http://videos.blinktower.com/medias/qahh1il5yt
![screen shot 2015-02-26 at 5 07 45 pm](https://cloud.githubusercontent.com/assets/2896608/6405582/0c1a5074-bdda-11e4-970b-447b85476d73.png)

If we have the original illustration file for the rocket itself we can probably do a cool parallax effect.

**Comment by sabrinang** [comment]
More screencap options 
0:23
![mozilla-webmaker_mobile-opportunity-mwc-2015-march_video-screenshot-2](https://cloud.githubusercontent.com/assets/2492510/6406771/8fffdeae-be02-11e4-9bc0-e8764d444ded.png)

1:18
![mozilla-webmaker_mobile-opportunity-mwc-2015-march_video-screenshot](https://cloud.githubusercontent.com/assets/2492510/6406774/96c3dfba-be02-11e4-9f25-52d9afa779c8.png)

**Comment by HPaulJohnson** [comment]
I vote for the last one (1:18)

**Comment by mmmavis** [comment]
Live on https://webmaker.org/localweb now.  (we picked the 1:18 one)
