### ISSUE TITLE
Disable / Grey-out link to India Report

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker.org#1346]
Doesn't look like we'll have the India report at 100% for the start of MWC as it still needs quite a bit of work. Let's keep the link on the page but disable it / grey it out. Once published, we can push an update.

/cc @mmmavis @LauraReynal @edrushka @secretrobotron @benrito

**Comment by edrushka** [comment]
cc @HPaulJohnson 

Sure thing, Andrew. Just let us know when it's ready.

**Comment by mmmavis** [comment]
Live on https://webmaker.org/localweb
