### ISSUE TITLE
Install Page - Refine content on desktop experience

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker.org#1347]
Got some solid feedback from @benrito this morning. The desktop experience of the install page is a little confusing as it's missing two pieces of information:
- That the app is a "beta"
- That the app is available on Android & Firefox OS

I don't think it requires a major change, but a little bit of additional messaging to the top copy block I think could get this clarified for the user. @secretrobotron can you work with @cadecairos and @k88hudson to get this resolved this morning?

**Comment by k88hudson** [comment]
I agree, this is pretty important

**Comment by secretrobotron** [comment]
:+1: 

@k88hudson think we should put little white versions of the FF and Android symbols beside (and under, on the skinny version) the "Get the App" button? I don't know where we'd put the "beta" info though.

Or, maybe just add a blurb beneath the button saying "This app is in public beta, and available for Android 4.4+ and FFOS 2.1+".

**Comment by k88hudson** [comment]
@secretrobotron can you sign off on this?

Change buttons to:
* Desktop: "Get Webmaker Beta"
* Mobile: "Download Webmaker Beta"

Design:
![image](https://cloud.githubusercontent.com/assets/1455535/6416144/e9bbbd5e-be71-11e4-967e-434218fe26ba.png)

**Comment by secretrobotron** [comment]
@k88hudson :+1:
