### ISSUE TITLE
Android 4.4 being recognized as Desktop

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker.org#1348]
User agent: 
```
Mozilla/5.0 (Linux; Android 4.4.4; D5803 Build/23.0.A.2.93) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.59 Mobile Safari/537.36
```

Expected: allows download.
Actual: shows desktop UI/SMS form

**Comment by k88hudson** [comment]
So it looks like the the reason for this is that our UA parser is not able to determine the device at all –

Perhaps we should use a more optimistic way of testing, i.e. explicitly showing the desktop UI if the type is `tablet` or `desktop` but show the mobile in all other cases

**Comment by secretrobotron** [comment]
@k88hudson fixed by https://github.com/k88hudson/webmaker.org/commit/e46503d998907c89903b5d4e7c2e274cf8b4e41b ?

**Comment by secretrobotron** [comment]
@k88hudson did you have another patch here? did you test? can we close?
