### ISSUE TITLE
Layout while gifs are loading (Install page)

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker.org#1352]
![screen shot 2015-02-27 at 13 47 58](https://cloud.githubusercontent.com/assets/1901816/6419006/ad91fbde-be87-11e4-8485-2ffaa1543da8.png)

`/app`

When on a slow connection (for example the rural and remote Toronto office :wink:) the phone illustration layout looks weird while the gifs are loading. 

Can we set this space to a white background behind the gif?

**Comment by thisandagain** [comment]
Good catch. @cadecairos do you think just setting the `background-color` to white is a good fix here?

**Comment by cadecairos** [comment]
certainly!
