### ISSUE TITLE
Crash when trying to edit an app

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1353]
Trying to edit an existing app. Webmaker app says it can't find it, but there's a crash, and an error.

![screenshot 2015-02-27 14 06 50](https://cloud.githubusercontent.com/assets/403231/6419286/e34ce91c-be89-11e4-88a9-2fde4d09d5eb.png)

```
Uncaught TypeError: Cannot read property 'id' of null index.js:15860
```

**Comment by thisandagain** [comment]
Hmm... do you have the `id` of the app?

**Comment by thisandagain** [comment]
Also can you move this over to the github.com/mozilla/webmaker-app repo?

**Comment by secretrobotron** [comment]
https://github.com/mozilla/webmaker-app/issues/1402
