### ISSUE TITLE
Login - Produce information architecture

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker.org#1364]
Produce information architecture documentation for login and sign-up flow. 
**Scenarios (x 2 - mobile & desktop):**

- [x] Sign-up
    - [x] Active states
    - [x] Error states
        - [x] Invalid email / phone number
        - [x] Empty email / phone number
        - [x] Username taken
        - [x] Invalid username
        - [x] Empty username
        - [x] Invalid password
        - [x] Empty password
        - ~~[ ] TOS not accepted~~
- [x] Login
    - [x] Active states
    - [x] Have password on file
    - [x] Have no password on file (migration)
- [x] Forgot password
    - [x] Active states
    - [x] Have no account on file (email / phone not found)
- [x] Email
    - [x] Token
    - [x] Forgot Password

/cc @cassiemc @xmatthewx

**Comment by thisandagain** [comment]
@cassiemc @xmatthewx @jbuck @simonwex Any user scenarios you see that I might be missing?

**Comment by xmatthewx** [comment]
- Sign-up - Email taken (shared address, forgot about account)
 - Login - Email account never confirmed
 - Forgot username / phone / email (forgot address used or lost access)
 - Forgot login method (login v5 - switched nascar sponsors, quit facebook)

**Comment by thisandagain** [comment]
These raise good questions / challenge a few assumptions:

**Do we want to continue to key off the email address AND username?**
I propose, no. We should switch to keying off the username only. This helps will classroom and internet cafe use cases.

**Do we want to confirm email addresses by confirmation link or by "soft" verification through something like BriteVerify?** I propose we pick a middle-ground by going with a system like BriteVerify (see planning ticket). That helps us greatly reduce the number of "throw away" accounts while still allowing us to not introduce a manual verification step for users.

**Are we pursuing any sort of social sign on in this sprint?** I propose "no" (for this SOW) but the new token-based system makes this easier to approach in the future.

**Where do we direct users who hit an unhandled edge case (lost access to email account, changed phone numbers, etc)?** We don't have a good answer to this right now outside of directing them towards @LucyeoH

**Comment by xmatthewx** [comment]
All sounds reasonable to me.

**Comment by cassiemc** [comment]
:+1:  nice thinking, folks.

**Comment by thisandagain** [comment]
One major update from the check-in meeting this morning:

I'm almost done with all the desktop cases (see below), but after talking about implementation with @jbuck (and my extreme desire to avoid the cross-tool head bashing we experienced in the last effort), I'd like to revise my mockups to propose that sign-up and log-in happen within a dedicated page rather than a modal. We have a few benchmarks that use this method ([CarbonMade](https://carbonmade.com/signup) is my current favorite) and it helps us avoid having to implement any sort session logic, JS, and CSS within each tool. Instead, tools would have "Sign Up" and "Log In" buttons that would link to something along the lines of:`https://webmaker.org/signup?r=popcorn.webmaker.org`. Once the user is done logging in or creating an account, the session cookie would be set, and the user would be redirected back to where they come from. Thoughts @simonwex ?

![flow_overview_20150305](https://cloud.githubusercontent.com/assets/747641/6511738/8be85cf8-c323-11e4-9c9c-903979495b71.png)
![flow_signup_20150205](https://cloud.githubusercontent.com/assets/747641/6511740/8d369b88-c323-11e4-8fed-df8bcb573b70.png)

**Comment by thisandagain** [comment]
Updated sign-up flow based on dedicated page concept (vs. modal):
![signup_desktop_20150205](https://cloud.githubusercontent.com/assets/747641/6513719/f063684a-c331-11e4-9c4f-e43c43b4452b.png)

**Comment by thisandagain** [comment]
Mobile sign-up flow:
![signup_mobile_20150205](https://cloud.githubusercontent.com/assets/747641/6520255/cca92a76-c376-11e4-98aa-3e202df82741.png)

**Comment by thisandagain** [comment]
Tracking spec details here: https://docs.google.com/presentation/d/1fkF7PBcvae3eDXTFVllLRz2Sk_gPPKqui9dsvuLY4h8/edit?usp=sharing

**Comment by thisandagain** [comment]
via @vazquez some documentation to support removing / toggling password masking: http://passwordmasking.com/

**Comment by thisandagain** [comment]
Final IA assets are available at:
`Google Drive > Product > login.webmaker.org > ia > flows`:

`signup_desktop_final.graffle`
`signup_mobile_final.graffle`
`login_desktop_final.graffle`
`login_mobile_final.graffle`
`email_final.graffle`

Please use these rather than the Google Slides for "final" assets as they include *all* the error and active states. PNG flats are also available in the `render` directory.

/cc @cassiemc @simonwex @jbuck

**Comment by thisandagain** [comment]
Reminder, if you don't have OmniGraffle, PNG versions of each flow (over 50 states in total) are available here:
`Google Drive > Product > login.webmaker.org > ia > render`

https://drive.google.com/folderview?id=0B-1AZgKn5Nc7ZFFBLW5ubVhQTHc&usp=sharing

/cc @davidascher @cassiemc @jbuck @secretrobotron @hannahkane
