### ISSUE TITLE
Login - Design UI for mobile

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker.org#1365]
Produce UI spec for login experience on desktop. Depends on #1364

**Comment by cassiemc** [comment]
Mobile signup here: http://invis.io/NH2FYKY5D

**Comment by cassiemc** [comment]
Design R? @thisandagain ?

**Comment by thisandagain** [comment]
Looks good @cassiemc . I'm guessing we'll just adapt the header to fit whatever navigation style / buttons we choose in the unified tool UI work? If so, R+ :+1:

**Comment by cassiemc** [comment]
Yes absolutely. That area is a blank slate as far as I am concerned. Moving on to 'sign up' today.

**Comment by thisandagain** [comment]
Awesome. Thanks.
