### ISSUE TITLE
Can't Access Homepage When Logged In 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/webmaker.org#1374]
When I'm logged into webmaker it won't let me access the homepage it just keeps redirecting me to explore. :(

**Comment by ScottDowne** [comment]
cc @thisandagain

**Comment by davidascher** [comment]
@thisandagain is on PTO.  Let's get other eyes on this, @simonwex,
@cadecairos, @k88hudson

**Comment by cadecairos** [comment]
I was told this was a "feature"

**Comment by ScottDowne** [comment]
I'm totally fine with simply removing the redirect. Our homepage has a bit going on now too with the privacy stuff.

**Comment by thisandagain** [comment]
As we don't have content on the splash page that makes sense for a logged-in user (the privacy day work is being removed / recycled) it does not make sense for a user with an account to hit `/`. In the absence of a "stream" or other user-specific dashboard for the time being it makes the most sense for users to be directed to `/explore`.
