### ISSUE TITLE
Settings tweaks to wiki.webmaker.org

### ISSUE THREAD

**Issue by OpenMatt** [mozilla/webmaker.org#1394]
* @jdotpz set up wiki.webmaker.org. It's been hugely valuable. I'd like to ask for help with three small tweaks:

- [x] 1) remove the dino head 
- [x] 2) remove the "tools" section from the sidebar. as mocked up [here] (https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/h1jhihob.png)
   - [(Documentation for how to do this)] (http://www.mediawiki.org/wiki/Manual:Interface/Sidebar)
- [x] 3) Allow external images. This is a simple settings change, documented [here] (http://www.mediawiki.org/wiki/Manual:$wgAllowExternalImages)

**Comment by OpenMatt** [comment]
Also: please allow external images. This is a simple settings change, as per
http://www.mediawiki.org/wiki/Manual:$wgAllowExternalImages

**Comment by OpenMatt** [comment]
Documentation: http://www.mediawiki.org/wiki/Manual:Skin_configuration

**Comment by OpenMatt** [comment]
Documentation: http://www.mediawiki.org/wiki/Manual:Skin_configuration

**Comment by OpenMatt** [comment]
4) bonus points: make the theme suck less. 
a) use the same theme we use for wiki.mozilla.org
b) apply the same CSS to it that we're using in either of these two places: book.webmaker.org or build.webmaker.org
c) switch to some other standard theme 
Whatever's easiest

**Comment by davidascher** [comment]
I suggest not using the same style as wiki.mozilla.org, cause doing so
would I think confuse people as to where they are.

**Comment by OpenMatt** [comment]
sounds good

**Comment by OpenMatt** [comment]
@jbuck : I'm going to spread this around next week, so if you could make the dino extinct by then, I'd be super grateful.

**Comment by jbuck** [comment]
Tweaks are done for now, @OpenMatt is going to look potential themes to install.

http://www.mediawiki.org/wiki/Category:All_skins
