### ISSUE TITLE
Disable current badge application flow

### ISSUE THREAD

**Issue by hannahkane** [mozilla/webmaker.org#1418]
We are going to roll out a new set of badges later this year. In the meantime, we want to prevent people from being able to apply for badges on Webmaker, as we don't have the staff to support them. Let's disable the "Apply" button on all badge pages and add an explanation, "We are no longer issuing this badge."

Any concerns with this plan, @thisandagain @davidascher @amirad @ldecoursy @chrislarry33 @thornet ?

**Comment by davidascher** [comment]
wfm

**Comment by amirad** [comment]
wfm

**Comment by thisandagain** [comment]
:+1:

**Comment by Pomax** [comment]
dev work tracked in https://github.com/mozilla/teach.mozilla.org/issues/1253

**Comment by omnignorant** [comment]
I know I'm super late to this party, but I'm just wondering what happens to existing badges and badge earners? What are we going to do with that data and can it be ported into the next thing? We had a good number of Chicago members earning badges.

**Comment by Pomax** [comment]
To the best of my knowledge, this work is only about making sure people can't click on links that don't work anymore (all the changes are to views in webmaker.org, not to the badges applications)

**Comment by omnignorant** [comment]
ok, so my concern must have been addressed someplace else, some other time. Still, if anyone has insight into my question, I would love to be informed.

**Comment by hannahkane** [comment]
@omnignorant - we're not losing the data on badges earned in the past; just preventing ppl from applying for badges that we're no longer supporting. Accessing previously-earned badges may be part of either the cred.ly implementation project, or the new profile project on teach.mozilla.org.
