### ISSUE TITLE
webmaker.org main page

### ISSUE THREAD

**Issue by kendallcorner** [mozilla/webmaker.org#1422]
Hello,
I tried to show some new coders your site and all the fun tools on it, but when I sent them to webmaker.org it redirected to a beta version of the site dealing with an app and with no link to the tools page.  I think thimble is pretty handy and great for new coders, so I'd like to be able to show them this feature next time.
Thanks!

**Comment by jbuck** [comment]
Hi @kendallcorner , you can visit Thimble directly at https://thimble.webmaker.org . We're currently in the process of [turning off some of our tools](https://blog.webmaker.org/whats-next-for-webmaker-tools) (Appmaker & Popcorn Maker), but [Thimble is in the process of getting an overhaul](https://blog.webmaker.org/whats-next-for-thimble).

**Comment by kendallcorner** [comment]
Oh, nice. Let me know if you want some help beta testing the new version.

**Comment by hannahkane** [comment]
Hey @kendallcorner - we would *love* help testing the new version. You can email me at hannah at mozillafoundation dot org for more info.

**Comment by hannahkane** [comment]
@xmatthewx, @thisandagain  - maybe we should talk about providing a pathway from webmaker to thimble and goggles.

**Comment by xmatthewx** [comment]
tracking here: https://github.com/mozilla/webmaker-browser/issues/170
