### ISSUE TITLE
'Turn off' Appmaker and Popcorn Maker

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/webmaker.org#1433]
This summer, we communicated to Webmaker.org users that both Appmaker and Popcorn Maker would become inaccessible on Wednesday, Sept. 30. (See [blog post](https://blog.webmaker.org/product-update-for-appmaker-and-popcorn-maker), or in-product banners, below.)

![screen shot 2015-09-30 at 3 02 32 pm](https://cloud.githubusercontent.com/assets/11045250/10203499/4ca42814-6784-11e5-8031-be2a03171254.png)

Are there plans in the works to 'turn off' both tools today/this week? Sorry if there's an existing ticket that covers this.

@xmatthewx @simonwex @HPaulJohnson

**Comment by cadecairos** [comment]
The deprecation plan has hit a few blockers, but is being tracked in mozillafoundation/plan#569

**Comment by simonwex** [comment]
@KevZawacki we're a bit behind on decommissioning. Do you see a problem with it happening later?

**Comment by KevZawacki** [comment]
@simonwex Do we have a date in sight? If it's < one week, shouldn't be an issue. If more, we may want to update our in-product banners.

**Comment by jbuck** [comment]
@KevZawacki tracking decommissioning in https://github.com/MozillaFoundation/mofo-devops/issues/205 and https://github.com/MozillaFoundation/mofo-devops/issues/206
