### ISSUE TITLE
Did webmaker stop issuing open badges?

### ISSUE THREAD

**Issue by kawpii** [mozilla/webmaker.org#1441]
Here I saw mentioning webmaker issue badges [here](https://wiki.mozilla.org/Badges/Issuers#Technology)
Then I saw this article over [here](https://learning.mozilla.org/blog/announcing-15-new-web-literacy-maker-badges#comment-69786) clicked the links of the new badges, but gave me 404s. Then I visited webmaker.org, it shows me Thimble (which allows to learn code with online code editor), I did not saw any thing about open badges. Since the article I mentioned was old(2014), I found article from 2016 over [here](https://learning.mozilla.org/blog/mozillas-continued-commitment-to-open-badges)

**My question is:  Did webmaker stop issuing open badges?**

**Comment by alanmoo** [comment]
Yes

**Comment by KaushalyaPradeep** [comment]
Thank you for the response
